bcgov/lcfs

.github/workflows/tests.yml, README.md, backend/lcfs/db/seeders/organization_seeder.py, backend/lcfs/db/seeders/organization_status_seeder.py, backend/lcfs/db/seeders/organization_type_seeder.py, backend/lcfs/db/seeders/role_seeder.py, backend/lcfs/db/seeders/seed_database.py, backend/lcfs/db/seeders/user_profile_seeder.py, backend/lcfs/db/seeders/user_role_seeder.py, frontend/.gitignore, frontend/cypress.config.js, frontend/cypress.env.json, frontend/cypress/e2e/user_flow.cy.js, frontend/cypress/support/commands.js, frontend/package.json, frontend/src/components/Login.js, frontend/src/components/Logout.js
This pull request introduces baseline Cypress integration tests for our application, ensuring quality and streamlining the development process.
**Note:** The related job in the GitHub workflow needs to be tested.
Closes #180
=> Feat: Implement Baseline Cypress Integration Tests - 180

frontend/src/components/BCTable.jsx, frontend/src/layouts/Layout.jsx, frontend/src/views/viewUsers/ViewUsers.jsx
quick table fix to remove enterprise module and column def data configuration that was causing crashes as well as a tiny improvement to component flexibility
=> fix: table example

frontend/src/components/Navbars/AppNavbar/Logout.jsx
=> Feat: Display User's Full Name in Top Banner - 155

backend/lcfs/web/api/user/schema.py, frontend/cypress/e2e/contact_us.cy.js, frontend/cypress/e2e/user_flow.cy.js, frontend/cypress/support/commands.js, frontend/package-lock.json, frontend/src/App.js, frontend/src/components/ContactUs.js, frontend/src/components/Footer.js, frontend/src/components/Login.js, frontend/src/components/Logout.js, frontend/src/components/Navbars/AppNavbar/Logout.jsx, frontend/src/constants/routes.js, frontend/src/layouts/Layout.jsx, frontend/src/layouts/PublicLayout.jsx, frontend/src/styles/Login.scss
This pull request adds a new Contact Us page and a 'Trouble logging in?' hyperlink to the login page.
**Additional improvements include:**
- Cypress tests for the new features.
- Refactoring of the login command.
- Renaming the 'logout' data-test attribute to 'logout-button'.
*Please note that styling will be added later.*
Closes #171
=> Feat: Implement Contact Us Page and Login Help Link - 171

backend/lcfs/db/seeders/dev/organization_address_seeder.py, backend/lcfs/db/seeders/dev/organization_attorney_address_seeder.py, backend/lcfs/db/seeders/dev/organization_seeder.py, backend/lcfs/db/seeders/dev_seeder.py, frontend/package-lock.json
added seeders for:
- organizations
- org addresses
- org attorney addreses
=> Feat: org seeders #241

backend/lcfs/conftest.py, backend/lcfs/db/seeders/test/test_user_profile_seeder.py, backend/lcfs/db/seeders/test/test_user_role_seeder.py, backend/lcfs/services/keycloak/authentication.py, backend/lcfs/services/keycloak/dependencies.py, backend/lcfs/tests/test_auth_middleware.py
- Added test_keycloak_user option to authentication.py
- Updated fixture with db_session_factory
- Created tests for user auth scenarios
=> Feat: Auth Middleware Pytests - 183

backend/lcfs/db/seeders/dev/user_profile_seeder.py, frontend/src/components/Role.jsx, frontend/src/constants/roles.js, frontend/src/utils/withRole.jsx, frontend/src/views/Dashboard/Dashboard.jsx, frontend/src/views/Dashboard/components/BCeIDRightColWidget.jsx, frontend/src/views/Dashboard/components/IDIRRightColWIdget.jsx
- feat: roles constants with `govRoles` and `nonGovRoles` groups for easy application
- fix: auth issue not finding first/last name in db (?)
- fix: `Roles` component and `withRole` HOC not finding roles on the current user
- feat: IDIR admin widget
=> feat: idir right col dashboard widget

README.md, backend/lcfs/web/api/organization/schema.py, frontend/.gitignore, frontend/cypress.config.js, frontend/cypress/e2e/user_flow.cy.js, frontend/cypress/support/commands.js, frontend/package-lock.json, frontend/package.json, frontend/src/layouts/MainLayout/components/Navbar.jsx, frontend/src/views/Login.jsx
- Updated Cypress config to use local environment variables for IDIR and BCeID credentials
- Updated Auth Cypress Tests
- Added forced logout to cypress login on failed attempts
=> Chore: Auth E2E Tests - 184

frontend/src/views/ViewOrg.jsx
note: using dummy data while waiting for test orgs accounts to be set up.
- fix: user model to better reflect backend model for easy switchover when test org accounts are set up
- fix: ag grid to pull in and format new user model data.
- feat: hide roles column when viewing inactive users.
=> fix: hide roles for inactive users #131

frontend/cypress/e2e/disclaimer_banner.cy.js, frontend/src/components/DisclaimerBanner.jsx, frontend/src/components/DisclaimerBanner.test.jsx, frontend/src/layouts/MainLayout/MainLayout.jsx
This PR adds legal and privacy disclaimers to the application.
The legal disclaimer is only visible to BCeID users, while the privacy disclaimer is visible to both IDIR and BCeID users.
Closes #137
=> Feat: Privacy and legal disclaimers - 137

backend/lcfs/web/api/organization/views.py
- fixed a syntax bug on organization view
=> Fix: Syntax Fix

backend/lcfs/web/api/organization/schema.py, backend/lcfs/web/api/organization/session.py, backend/lcfs/web/api/organization/views.py, backend/lcfs/web/api/role/views.py, backend/lcfs/web/api/user/views.py, backend/lcfs/web/lifetime.py, frontend/src/hooks/useOrganization.js, frontend/src/hooks/useRole.js, frontend/src/hooks/useUser.js, frontend/src/themes/base/breakpoints.js, frontend/src/themes/base/globals.js, frontend/src/themes/base/typography.js, frontend/src/views/AdminMenu/components/Roles.jsx, frontend/src/views/AdminMenu/components/Users.jsx, frontend/src/views/Login.jsx, frontend/src/views/Organizations/Organizations.jsx, frontend/src/views/Organizations/components/ViewOrg.jsx, frontend/src/views/Transactions/Transactions.jsx, frontend/src/views/Transactions/components/OrganizationList.jsx
LCFS - IDIR users can filter transactions by organization#192
=> Feat: LCFS - IDIR users can filter transactions by organization #192

frontend/src/views/AddTransaction/AddTransaction.jsx, frontend/src/views/AddTransaction/components/TransferDetails.jsx, frontend/src/views/AddTransaction/components/TransferGraphic.jsx
This pull request introduces a dynamic graphic on the new transfers page, updating in real-time based on user-entered transfer details.
Screenshots:
Closes #215
=> Feat: Transfer graphic component - 215

frontend/src/views/AddTransaction/AddTransaction.jsx, frontend/src/views/AddTransaction/components/Comment.jsx, frontend/src/views/AddTransaction/components/TransferDetails.jsx, frontend/src/views/AddTransaction/components/TransferGraphic.jsx
_Before reviewing this, please merge PR #352 first because this branch started from there._
This pull request introduces a collapsible comment section on the transfer page, enhancing user interaction and providing a space for relevant information exchange.
Screenshots:
Closes #217
=> Feat: Transfer comment component - 217

backend/lcfs/db/models/UserProfile.py, backend/lcfs/web/api/organization/repo.py, backend/lcfs/web/api/organization/schema.py, backend/lcfs/web/api/organization/services.py, backend/lcfs/web/api/organization/views.py, backend/lcfs/web/api/transaction/schema.py, backend/lcfs/web/api/transaction/session.py, backend/lcfs/web/api/user/schema.py
This PR standardizes organization module's Pydantic schemas, improving readability and easing future updates.
Closes #307
=> Feat: Standardize Pydantic schema classes in organization module - 307

backend/migrate.sh
This PR introduces a new option for reseting and seeding the database.
Closes #372
=> Feat: Add Reseting & Seeding option to migration script - 372

backend/lcfs/web/api/organization/repo.py, backend/lcfs/web/api/organization/schema.py, backend/lcfs/web/api/organization/services.py, backend/lcfs/web/api/organization/views.py, frontend/src/views/Organizations/AddOrganization/_schema.js
This PR resolves the save error encountered by IDIR users when creating new Organizations and updates the postal code validation to improve data integrity and UX.
Closes #161
=> Fix: Org Creation Error and Postal Code Formatting - 161

backend/lcfs/db/seeders/dev/user_profile_seeder.py, backend/lcfs/db/seeders/dev/user_role_seeder.py, backend/lcfs/web/api/transaction/views.py, frontend/src/views/Transactions/Transactions.jsx, frontend/src/views/Transfers/AddEditTransfer/AddEditTransfer.jsx
- updated user profile role seeds
- transfer permission fixes
=> Fix: Seed updates

.github/workflows/dev-ci.yml, backend/lcfs/db/seeders/dev/user_profile_seeder.py, backend/lcfs/db/seeders/dev/user_role_seeder.py, backend/lcfs/web/api/transaction/views.py, backend/lcfs/web/api/user/repo.py, backend/lcfs/web/api/user/services.py, frontend/Dockerfile.openshift, frontend/nginx.conf, frontend/src/App.jsx, frontend/src/components/BCAlert/BCAlertRoot.jsx, frontend/src/components/BCAlert/index.jsx, frontend/src/components/BCDataGrid/BCDataGridServer.jsx, frontend/src/components/BCForm/BCFormCheckbox.jsx, frontend/src/themes/base/typography.js, frontend/src/themes/components/form/checkbox.js, frontend/src/themes/components/form/radio.js, frontend/src/views/Admin/AdminMenu/components/Users.jsx, frontend/src/views/Admin/AdminMenu/components/ViewUser.jsx, frontend/src/views/Admin/AdminMenu/components/_schema.js, frontend/src/views/Organizations/ViewOrganization/ViewOrganization.jsx, frontend/src/views/Transactions/Transactions.jsx, frontend/src/views/Transfers/AddEditTransfer/AddEditTransfer.jsx, frontend/src/views/Users/AddEditUser/AddEditUser.jsx, frontend/src/views/Users/AddEditUser/_schema.js, frontend/src/views/Users/AddEditUser/components/BCeIDSpecificRoleFields.jsx, frontend/src/views/Users/AddEditUser/components/IDIRSpecificRoleFields.jsx, openshift/templates/knps/allow-crunchy-accept.yaml, openshift/templates/knps/allow-redis-accept.yaml
=> Edit idir user and BCeid user create/update fixes

backend/lcfs/web/api/user/views.py, backend/lcfs/web/core/decorators.py, frontend/src/views/Organizations/ViewOrganization/ViewOrganization.jsx
- fix: role decorator bug
- fix: bceid users not being bale to load users on the org page
=> fix: bceid org view

frontend/src/assets/locales/en/organization.json, frontend/src/views/Organizations/AddEditOrg/AddEditOrg.jsx
#402 
- fix: radio not populating when editing an org
- fix: add/edit title fix
=> fix: radio not populating with default value on edit org 402

frontend/src/views/Organizations/AddEditOrg/AddEditOrg.jsx
=> fix: addedit org bug

frontend/index.html
=> Revert "fix: config"

backend/lcfs/web/api/role/repo.py, backend/lcfs/web/api/role/services.py, backend/lcfs/web/api/role/views.py, backend/lcfs/web/api/user/services.py, frontend/src/components/BCDataGrid/BCColumnSetFilter.jsx, frontend/src/components/BCDataGrid/BCDataGridServer.jsx, frontend/src/components/DataGridLoading.jsx, frontend/src/constants/routes/apiRoutes.js, frontend/src/hooks/useRole.js, frontend/src/themes/components/menu/index.js, frontend/src/themes/components/menu/menuItem.js, frontend/src/utils/cellRenderers.jsx, frontend/src/views/Admin/AdminMenu/components/Users.jsx, frontend/src/views/Admin/AdminMenu/components/_schema.js, frontend/src/views/Organizations/ViewOrganization/ViewOrganization.jsx, frontend/src/views/Organizations/ViewOrganization/_schema.js
=> Fix: LCFS - IDIR Users table showing BCeID users and incorrect roles -391

backend/lcfs/web/api/organization/services.py, frontend/src/components/Login.jsx, frontend/src/views/Dashboard/components/idirWidgets/AdminLinksCard.jsx
#130 
-- fix for default inactive users filter.
=> Fix: LCFS - Filter out inactive users by default in the user tables #130

frontend/src/views/Organizations/AddEditOrg/AddEditOrg.jsx
#402 
- fix: typo causing page to not navigate after form success
=> fix: Edit org navigate on success 

frontend/src/assets/locales/en/transaction.json, frontend/src/views/Transactions/Transactions.jsx
=> Fix: Update transfer button label - 212

backend/lcfs/web/api/transaction/repo.py, backend/lcfs/web/api/transfer/repo.py, backend/lcfs/web/api/transfer/services.py, frontend/src/assets/locales/en/transfer.json, frontend/src/hooks/useCurrentUser.js, frontend/src/views/Transfers/ViewTransfer/ViewTransfer.jsx, frontend/src/views/Transfers/buttonConfigs.js
This PR introduces the ability for organizations to decline a transfer proposal.
Closes #250
=> Feat: Implement Decline Transfer Functionality - 250

frontend/src/App.jsx, frontend/src/constants/routes/apiRoutes.js, frontend/src/utils/cellRenderers.jsx, frontend/src/utils/formatters.js, frontend/src/views/Admin/AdminMenu/components/_schema.js, frontend/src/views/Organizations/Organizations.jsx, frontend/src/views/Organizations/ViewOrganization/ViewOrganization.jsx, frontend/src/views/Organizations/ViewOrganization/_schema.js, frontend/src/views/Transactions/_schema.js, frontend/src/views/Transfers/AddEditTransfer/AddEditTransfer.jsx, frontend/src/views/Transfers/AddEditTransfer/components/AgreementDate.jsx, frontend/src/views/Transfers/AddEditTransfer/components/TransferSummary.jsx, frontend/src/views/Transfers/ViewTransfer/ViewTransfer.jsx, frontend/src/views/Transfers/components/AddPlainComment.jsx, frontend/src/views/Transfers/components/index.js, frontend/src/views/Users/AddEditUser/AddEditUser.jsx
- To wrap the roles in ag-grid, to adjust the row height.
- Add new organization user navigation issues for IDIR users.
- Links to enable to open in new tab.
- missing AddPlainComment component.
=> fix: styling & navigation fixes

frontend/src/views/Transfers/AddEditTransfer/AddEditTransfer.jsx
#454 
- fix: transfer and signing auth roles having 'sign and send' button disabled on new transfer
=> fix: sign and send disabled for new transfers for certain roles

frontend/src/assets/locales/en/transfer.json, frontend/src/components/BCModal.jsx, frontend/src/views/Transfers/AddEditTransfer/AddEditTransfer.jsx, frontend/src/views/Transfers/ViewTransfer/ViewTransfer.jsx, frontend/src/views/Transfers/buttonConfigs.js
#316 
- refactor: consolidated button styling config
- feat: Director role IDIR users can return transfer to analyst
=> feat: director can return transfer to analyst

backend/lcfs/web/api/organization/views.py
Fix for minor bug found while trying to create a user via BCeID user.
=> Fix: Organization User create bug fix

backend/lcfs/tests/test_access_control.py, backend/lcfs/tests/test_audit_events.py, backend/lcfs/tests/test_users.py, backend/lcfs/tests/transaction/test_transaction_services.py, backend/lcfs/tests/transfer/test_transfer_repo.py, backend/lcfs/tests/transfer/test_transfer_services.py, backend/lcfs/web/api/transaction/repo.py
- fixed backend unit tests for new user config
- updated query logic for org transactions to not return other org txns
=> Fix: Updated Org Transactions

backend/lcfs/web/api/organizations/views.py, frontend/src/hooks/useOrganization.js, frontend/src/layouts/MainLayout/components/HeaderComponent.jsx
- feat: show total and reserve balance in header, closes #156 
- feat: store preference in session storage, closes #129
=> feat: balance in header

backend/lcfs/web/api/transfer/repo.py, backend/lcfs/web/api/transfer/schema.py, backend/lcfs/web/api/transfer/services.py, frontend/src/views/Transfers/AddEditTransfer/AddEditTransfer.jsx
- feat: ability to sign and send transfer, closes #454 
- fix: unable to sign and send transfer, closes #489
=> feat: sign and send transfer

frontend/src/layouts/MainLayout/components/HeaderComponent.jsx
- fix: balance to show as default in nav, closes #129
=> fix: switch balance to show as default

backend/lcfs/db/migrations/versions/2024-03-22-13-08_0ad956decbc4.py, backend/lcfs/db/models/Transfer.py, backend/lcfs/db/models/TransferHistory.py, backend/lcfs/web/api/transfer/repo.py, backend/lcfs/web/api/transfer/schema.py, backend/lcfs/web/api/transfer/services.py, frontend/src/assets/locales/en/transfer.json, frontend/src/views/Transfers/AddEditViewTransfer.jsx, frontend/src/views/Transfers/components/TransactionHistory.jsx, frontend/src/views/Transfers/components/TransferHistory.jsx, frontend/src/views/Transfers/components/TransferView.jsx
- migration adding user_profile to transfer_history table
- hooked up real data for transfer history list
- created a separate transfer history component
- added dynamic labelling based on transfer status for history list
=> Feat: Transfer History List - 478

backend/lcfs/web/api/internal_comment/repo.py, backend/lcfs/web/api/transaction/repo.py, backend/lcfs/web/api/transfer/services.py, frontend/src/components/InternalComments/index.jsx
- updated statuses checked on transactions list for gov users
- fixed rescind release of compliance units
=> Fix: logic fixes for transfer workflow

backend/lcfs/db/migrations/versions/2024-04-03-14-02_b2b46ce7d6bc.py, backend/lcfs/db/migrations/versions/2024-04-03-14-02_df41556bd1ee.py
- Removed errant table creation on sqlalchemy auto create
- Added triggers and views for transaction lookups
=> Fix: materialized view fixes

backend/lcfs/db/migrations/versions/2024-04-03-14-02_b2b46ce7d6bc.py, backend/lcfs/db/models/Transfer.py, backend/lcfs/db/seeders/test/test_transfer_seeder.py, backend/lcfs/tests/internal_comment/internal_comment_payloads.py, backend/lcfs/tests/payloads.py, backend/lcfs/tests/transaction/transaction_payloads.py, backend/lcfs/tests/transfer/transfer_payloads.py, backend/lcfs/web/api/organization/validation.py, backend/lcfs/web/api/transfer/schema.py, backend/lcfs/web/api/transfer/services.py
- no longer need bool signing authority declaration so removed from transfer model and tests
=> Chore: remove signing authority boolean from transfer

backend/lcfs/web/api/organization/validation.py, backend/lcfs/web/api/organizations/services.py, backend/lcfs/web/api/transfer/validation.py, backend/lcfs/web/api/transfer/views.py, frontend/src/components/BCAlert/index.jsx, frontend/src/layouts/MainLayout/components/HeaderComponent.jsx, frontend/src/layouts/MainLayout/components/SupplierBalance.jsx, frontend/src/views/Transfers/AddEditViewTransfer.jsx, frontend/src/views/Users/AddEditUser/AddEditUser.jsx
- Added backend validation on transfer create and update to ensure Suppliers can't create transfers with a quantity greater than their compliance units balance
- Added a ref to BCAlert so it can render multiple times on click
- Fixed render bug on org user display
- Conditional rendering of supplier balance added to header component
- Formatting in supplier balance fixed
=> Feat: Transfer Balance Validation

frontend/src/components/InternalComments/index.jsx, frontend/src/views/Transfers/components/TransferView.jsx
This PR fixes CORS issue for analyst role, ensuring correct network access.
Reported issue:
https://github.com/bcgov/lcfs/issues/312#issuecomment-2038410961
Closes #312, #259
=> Fix: Correct CORS Issue for Analyst Role Access - 312, 259

backend/lcfs/conftest.py, backend/lcfs/db/migrations/versions/2024-04-15-20-52_d781da2e8de1.py, backend/lcfs/db/models/Organization.py, backend/lcfs/tests/organizations/__init__.py, backend/lcfs/tests/organizations/organizations_payloads.py, backend/lcfs/tests/organizations/test_organizations_repo.py, backend/lcfs/tests/transfer/test_status_changes.py, backend/lcfs/web/api/organizations/schema.py, frontend/src/views/Organizations/ViewOrganization/_schema.js
This PR updates the organization list view to include compliance unit balance and in reserve balance, improving transparency and accessibility for users.
Closes #507
=> Feat: Update Organization List View to Display Compliance and Reserve Balances - 507

backend/lcfs/web/api/organizations/schema.py, backend/lcfs/web/api/organizations/views.py
- updated organization update from the idir side to use the proper pydantic class.
=> Fix: Org Edit Schema - 572

frontend/src/assets/locales/en/transaction.json, frontend/src/layouts/MainLayout/components/SupplierBalance.jsx
#464 - bug fix
org balance defaulting to hidden fix
=> bug fix -464

backend/lcfs/tests/transfer/test_transfer_repo.py, backend/lcfs/web/api/transfer/repo.py, backend/lcfs/web/api/transfer/services.py
- if the transfer is returned to analyst then no history recorded is added.
- if the transfer is recommended again to director then update the existing history record.
- Ensure when the transfer is in submitted status, previously recommended history is not show to the users.
=> LCFS - Visibility issue- IDIR activity being reflected on BCeID action history #585

backend/lcfs/web/api/transfer/services.py
=> Bug fix for transfer.

frontend/src/assets/locales/en/fuelCode.json, frontend/src/views/FuelCodes/ViewFuelCode/ViewFuelCode.jsx
- fix: fuel code not invalidating
- fix: missing delete success message
=> fix - 436, 441

backend/lcfs/db/seeders/dev/feedstock_fuel_transfer_mode_seeder.py, backend/lcfs/db/seeders/dev/finished_fuel_transfer_mode_seeder.py, backend/lcfs/db/seeders/dev/fuel_code_seeder.py, backend/lcfs/db/seeders/dev_seeder.py, backend/lcfs/web/api/fuel_code/repo.py, backend/lcfs/web/api/fuel_code/schema.py, backend/lcfs/web/api/fuel_code/services.py, backend/lcfs/web/api/fuel_code/views.py, frontend/src/components/BCDataGrid/BCDataGridEditor.jsx, frontend/src/components/BCDataGrid/components/Editors/AutocompleteEditor.jsx, frontend/src/components/BCDataGrid/components/Renderers/ActionsRenderer.jsx, frontend/src/views/FuelCodes/AddFuelCode/AddFuelCode.jsx, frontend/src/views/FuelCodes/AddFuelCode/_schema.jsx
- feat: auto suggest text for fuel codes 'fuel code' field, closes #434
=> feat: fuel code auto suggest text

frontend/src/App.jsx, frontend/src/assets/locales/en/reports.json, frontend/src/constants/routes/routes.js, frontend/src/i18n.js, frontend/src/utils/cellRenderers.jsx, frontend/src/views/ComplianceReports/ComplianceReports.jsx, frontend/src/views/ComplianceReports/_schema.js
- Compliance report index page.
Note: Test cases and data testing will be done once the backend tables are created.
=> LCFS - Compliance reporting index #604

backend/lcfs/web/api/admin_adjustment/schema.py, backend/lcfs/web/api/admin_adjustment/services.py
This PR resolves the issue of internal commenting on new admin adjustment transaction.
Closes #347
=> Fix: Resolve internal comments issue on administrative adjustment - 347

frontend/src/components/BCDataGrid/components/Editors/AutocompleteEditor.jsx, frontend/src/constants/common.js, frontend/src/views/FuelCodes/AddFuelCode/_schema.jsx
- fix: fuel code logic, closes #434
=> Fix - fuel code predictive text logic fix

frontend/src/views/FuelCodes/_schema.jsx
There was a bug preventing draft fuel codes from being saved or being approved due to the view fuel code page schema not including the new location fields.
- fix: view fuel code schema
=> fix: view fuelcode schema

backend/lcfs/db/migrations/versions/2024-06-11-12-48_ca01318d5925.py, backend/lcfs/db/models/fuel/FuelCategory.py, backend/lcfs/db/models/fuel/FuelClass.py, backend/lcfs/db/models/fuel/FuelType.py, backend/lcfs/db/seeders/common/fuel_data_seeder.py, backend/lcfs/db/seeders/common/seed_fuel_data.json
This PR adds fuel category options for fuel types in the backend data tables.
Closes #541
=> Feat: Add Fuel Category Options for Fuel Types - 541

frontend/src/components/BCAlert/index.jsx, frontend/src/themes/base/colors.js, frontend/src/views/FuelCodes/AddFuelCode/AddFuelCode.jsx
- feat: added pending state
- feat: added text expand feature when text is longer than 1 line
- feat: added `noFade` prop
closes, #609 
keeps same implementation as before using `<BCAlert/>`
```js
// triggering the alert
alertRef.current.triggerAlert()
<BCAlert
ref={alertRef}
data-test="alert-box"
severity={alertSeverity} // pending, warning, error, success
delay={5000}
>
{alertMessage} // the message for the alert
</BCAlert>
```
=> Feat: validation banner component

frontend/src/views/FuelCodes/AddFuelCode/_schema.jsx
- fix: Optional fields were showing validation errors, fixes #647
=> fix: optional fuelcode field validation

frontend/src/views/FuelCodes/AddFuelCode/AddFuelCode.jsx, frontend/src/views/FuelCodes/_schema.jsx
- fix: last updated field for fuel codes. hide for new/edit, show for approved. set to PST time, fixes #623
=> fix: last update field

frontend/package-lock.json, frontend/package.json, frontend/src/components/BCDataGrid/BCDataGridEditor.jsx
=> LCFS - Spike - Investigate pasting from Excel into AG Grid #655

frontend/src/views/FuelCodes/AddFuelCode/_schema.jsx
- fix: fix validation on fuel codes where former company should be optional, fixes #647
=> fix: former company validation

backend/lcfs/web/api/compliance_report/repo.py, backend/lcfs/web/api/compliance_report/schema.py, backend/lcfs/web/api/compliance_report/services.py, backend/lcfs/web/api/compliance_report/validation.py, backend/lcfs/web/api/compliance_report/views.py
- feat: backend work for fuel for other uses, closes #637
=> feat: backend for fuel for other uses

backend/lcfs/web/api/notional_transfer/repo.py, backend/lcfs/web/api/notional_transfer/schema.py, backend/lcfs/web/api/notional_transfer/services.py, backend/lcfs/web/api/notional_transfer/views.py, frontend/src/assets/locales/en/notionalTransfer.json, frontend/src/components/BCDataGrid/BCDataGridServer.jsx, frontend/src/constants/routes/apiRoutes.js, frontend/src/hooks/useNotionalTransfer.js, frontend/src/views/ComplianceReports/ComplianceReports.jsx, frontend/src/views/ComplianceReports/components/AddEditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/components/ReportDetailsAccordion.jsx, frontend/src/views/NotionalTransfers/AddEditNotionalTransfers.jsx, frontend/src/views/NotionalTransfers/NotionalTransferSummary.jsx
- Added notional transfer summary table to compliance report view
- Added pagination endpoint for notional transfers
=> Feat: Notional transfer summary table - 659

backend/lcfs/web/api/transaction/services.py
- fix: transaction download filter not filtering "Approved" and "Recorded" only, fixes #193
=> fix: transaction download filter

backend/lcfs/web/api/fuel_code/schema.py, frontend/src/views/FuelCodes/_schema.jsx
- fix: `contactName` and `contactEmail` optional, fixes #647
=> fix: contact name and email optional

backend/lcfs/db/seeders/common/seed_fuel_data.json, frontend/src/views/FuelCodes/_schema.jsx
- feat: add new fuel code prefix to seed file, closes #696
=> Add new fuel code prefix

frontend/src/views/FuelCodes/AddFuelCode/_schema.jsx, frontend/src/views/FuelCodes/_schema.jsx
- feat: move ci and edmrs columns
=> feat: move fuel code columns

backend/lcfs/web/api/fuel_code/services.py, frontend/src/views/FuelCodes/AddFuelCode/AddFuelCode.jsx, frontend/src/views/FuelCodes/ViewFuelCode/ViewFuelCode.jsx, frontend/src/views/FuelCodes/_schema.jsx
- fix: facility nameplate capacity units not showing on view fuel code, fixes #702
=> fix: facility nameplate capacity units not showing on view fuel code

backend/lcfs/web/api/dashboard/views.py, backend/lcfs/web/api/fuel_code/services.py, backend/lcfs/web/api/organization/views.py, backend/lcfs/web/api/transaction/views.py, frontend/src/assets/locales/en/fuelCode.json, frontend/src/views/FuelCodes/AddFuelCode/AddFuelCode.jsx, frontend/src/views/FuelCodes/_schema.jsx
- fix: FP location not showing in fuel code list view in grid, closes #727
=> Fix:FP location not showing in fuel code list view in grid 727

backend/lcfs/web/api/dashboard/views.py, backend/lcfs/web/api/fuel_code/services.py, backend/lcfs/web/api/organization/views.py, backend/lcfs/web/api/transaction/views.py
- fix: backend role errors due to using deprecated methods of RBAC
=> fix: backend role errors

backend/lcfs/web/api/compliance_report/views.py, backend/lcfs/web/api/dashboard/views.py, backend/lcfs/web/api/final_supply_equipment/views.py, backend/lcfs/web/api/initiative_agreement/views.py, backend/lcfs/web/api/organization/views.py, backend/lcfs/web/api/organizations/views.py, backend/lcfs/web/api/transaction/views.py, backend/lcfs/web/api/transfer/views.py, frontend/src/assets/locales/en/common.json, frontend/src/components/BCDataGrid/BCDataGridEditor.jsx, frontend/src/components/BCDataGrid/components/Editors/DateRangeCellEditor.jsx, frontend/src/hooks/useComplianceReports.js, frontend/src/hooks/useOtherUses.js, frontend/src/utils/cellRenderers.jsx, frontend/src/views/ComplianceReports/ComplianceReports.jsx, frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx, frontend/src/views/ComplianceReports/components/Introduction.jsx, frontend/src/views/ComplianceReports/components/NewComplianceReportButton.jsx, frontend/src/views/ComplianceReports/components/ReportDetails.jsx, frontend/src/views/FinalSupplyEquipments/FinalSupplyEquipmentSummary.jsx, frontend/src/views/FinalSupplyEquipments/_schema.jsx, frontend/src/views/OtherUses/AddEditOtherUses.jsx
- #714 (FSE date range defaulted)
- DateRangeCellEditor bug fix for UTC date format.
- fix for ```request: Request``` missing positional parameter updates on all the views files on backend, which was causing issues on some of the endpoints
- Add Floating button to scroll up or down with a click on compliance report.
- CommonArray cell Renderer styling fix in case of read only ag-grid
- compliance period endpoint to be cached 
- once the new compliance report button is clicked by choosing the compliance year this button will show loading and disable any click actions on it.
- Show Introduction accordion expanded only when a new report is created.
=> Feat: LCFS - FSE date range default #714

backend/lcfs/web/api/compliance_report/services.py
- feat: stub of line 19, closes #758 
note: replace stub with sum of export fuels later
=> feat: line 19 of compliance report summary

frontend/src/views/Admin/__tests__/Admin.test.jsx, frontend/src/views/Admin/__tests__/AdminTabPanel.test.jsx, frontend/src/views/Admin/__tests__/Menu.test.jsx, frontend/src/views/Admin/__tests__/Users.test.jsx, frontend/src/views/Admin/__tests__/ViewUser.test.jsx, frontend/src/views/Admin/__tests__/_schema.test.js
- Added unit tests for pages: Admin, AdminTabPanel, Menu, Users, ViewUser
=> Feat: Admin Views Unit Tests - 553

backend/lcfs/web/api/compliance_report/constants.py, backend/lcfs/web/api/compliance_report/services.py
- feat: calculations for line 11, non compliance penalty calculations, closes #738
=> feat: non compliance penalty calculation 738

backend/lcfs/web/api/compliance_report/services.py, frontend/src/views/ComplianceReports/components/SummaryTable.jsx
- fix: calculate and display negative values for line 5 and 10, #733 #737
- modifies table to display negative values in parenthesis ( without the negative symbol )
=> fix: summary line 5 negative values

backend/lcfs/conftest.py, backend/lcfs/db/seeders/dev/organization_seeder.py, backend/lcfs/db/seeders/test/test_admin_adjustment_seeder.py, backend/lcfs/db/seeders/test/test_organization_seeder.py, backend/lcfs/db/seeders/test/test_transaction_seeder.py, backend/lcfs/db/seeders/test_seeder.py, backend/lcfs/tests/admin_adjustment/test_admin_adjustment.py, backend/lcfs/tests/test_auth_middleware.py, backend/lcfs/tests/test_organization.py, backend/lcfs/tests/test_users.py, backend/lcfs/web/api/admin_adjustment/services.py, backend/lcfs/web/api/admin_adjustment/validation.py, backend/lcfs/web/api/admin_adjustment/views.py, backend/lcfs/web/api/organizations/views.py
#303 
- fixes for admin-adjustment test cases.
=> LCFS - Implement Pytest Unit Tests for Organization Views in FastAPI Backend

frontend/src/assets/locales/en/fuelSupply.json, frontend/src/views/FuelSupplies/FuelSupplySummary.jsx
This PR resolves the issue with column headings not displaying properly in the Fuel Supply section. 
Closes #717
=> Fix: Resolve Column Heading Display Issue in Fuel Supply Section - 717

backend/lcfs/web/api/compliance_report/schema.py, backend/lcfs/web/api/compliance_report/summary_service.py, frontend/src/views/ComplianceReports/components/SummaryTable.jsx
line 11 fix to display monetary value and logic to display blank when value is 0
closes #738
=> fix: line 11 - 738

frontend/src/views/OtherUses/AddEditOtherUses.jsx
- fix: fixes an error when saving other uses rows, closes #807
=> fix: other uses save errors 807

backend/lcfs/services/keycloak/authentication.py, backend/lcfs/web/api/compliance_report/constants.py, backend/lcfs/web/api/compliance_report/schema.py, backend/lcfs/web/api/compliance_report/summary_service.py, frontend/src/views/ComplianceReports/components/SummaryTable.jsx
=> Feat: Summary line 21 calculations

backend/lcfs/db/migrations/versions/2024-08-16-14-43_0d1869d6ae12.py, backend/lcfs/db/models/compliance/ComplianceReport.py, backend/lcfs/db/models/compliance/FuelSupply.py, backend/lcfs/tests/compliance_report/test_compliance_report_services.py, backend/lcfs/web/api/compliance_report/repo.py, backend/lcfs/web/api/compliance_report/summary_service.py, backend/lcfs/web/api/fuel_supply/services.py, frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx
- Added calculation for fuel supply compliance units aggregation (Line 18)
- Added change type to fuel supply and implemented version aware totals
- Tests for compliance unit calculations
=> Feat: Summary Line 18 Calculations

frontend/src/assets/locales/en/finalSupplyEquipment.json, frontend/src/assets/locales/en/fuelCode.json, frontend/src/assets/locales/en/fuelSupply.json, frontend/src/assets/locales/en/notionalTransfer.json, frontend/src/assets/locales/en/otherUses.json
- fix: capitalization of 'Excel' on the frontend, closes #830
=> fix: excel capitalization - 830

backend/lcfs/web/api/compliance_report/summary_service.py, backend/lcfs/web/api/transaction/repo.py, frontend/src/assets/locales/en/reports.json
=> Feat: Line-17 Calculate and display available compliance unit balance for the compliance period.

backend/lcfs/web/api/compliance_report/summary_service.py
This PR adds the functionality to display the compliance unit change in Line 20 of the compliance summary for the current period.
Closes #779
=> Feat: Display Compliance Unit Change in Line 20 of Compliance Summary - 779

backend/lcfs/web/api/transaction/services.py, frontend/src/views/Transactions/_schema.js, frontend/src/views/Transfers/AddEditViewTransfer.jsx
This PR updates the prefix for Compliance Unit Transfer (CUT) to Credit Transfer (CT) throughout the portal.
Closes #842
=> Feat: Change Prefix from CUT to CT Across the Portal - 842

backend/Dockerfile, backend/lcfs/start.sh, backend/migrate.sh, docker-compose.yml
* Change scripts to use sh instead of bash as bash may not be present on the image
* Remove deprecated version tag from docker-compose
=> Update Base Image + Windows Fixes

frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx, frontend/src/views/FuelSupplies/FuelSupplySummary.jsx, frontend/src/views/FuelSupplies/_schema.jsx
* Fix error on initial load that data is not iterable
Closes https://github.com/bcgov/lcfs/issues/853
=> Move compliance units to first column

frontend/src/components/BCDataGrid/BCGridViewer.jsx, frontend/src/views/ComplianceReports/__tests__/EditViewComplianceReports.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/ComplianceReportSummary.test.jsx, frontend/src/views/FuelCodes/__tests__/FuelCodes.test.jsx, frontend/src/views/NotionalTransfers/__tests__/NotionalTransferSummary.test.jsx, frontend/src/views/Transfers/components/__tests__/TransferSummary.test.jsx
This PR fixes failing Jest tests for ComplianceReports, FuelCodes, and NotionalTransfers components.
Closes #873
=> Fix: Resolve Failing Frontend Tests for Key Components - 873

frontend/src/components/BCDataGrid/components/Editors/DateEditor.jsx
* Remove clearable true to hide the button
Closes: https://github.com/bcgov/lcfs/issues/863
=> feat: Remove clear button from Grid Date Editor

backend/lcfs/db/migrations/versions/2024-09-05-22-13_7883dc36d1b1.py, backend/lcfs/db/models/compliance/FuelSupply.py, backend/lcfs/tests/compliance_report/test_compliance_report_services.py, backend/lcfs/web/api/fuel_supply/schema.py, frontend/src/assets/locales/en/fuelSupply.json, frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx, frontend/src/views/FuelSupplies/FuelSupplySummary.jsx, frontend/src/views/FuelSupplies/_schema.jsx
* Rename in models, generate migration
* Update label and rename in front end
Closes: https://github.com/bcgov/lcfs/issues/852
=> feat: Rename CI Limit to Target CI

frontend/src/hooks/useOrganization.js, frontend/src/hooks/useOrganizations.js, frontend/src/views/Dashboard/components/cards/idir/OrganizationsSummaryCard.jsx, frontend/src/views/Dashboard/components/cards/idir/__tests__/OrganizationsSummaryCard.test.jsx, frontend/src/views/FuelCodes/AddFuelCode/_schema.jsx, frontend/src/views/FuelSupplies/_schema.jsx, frontend/src/views/NotionalTransfers/_schema.jsx, frontend/src/views/Organizations/AddEditOrg/__tests__/AddEditOrg.test.jsx, frontend/src/views/Organizations/ViewOrganization/_schema.js, frontend/src/views/OtherUses/_schema.jsx, frontend/src/views/Transactions/__tests__/AddEditViewTransaction.test.jsx, frontend/src/views/Transactions/__tests__/Transactions.test.jsx, frontend/src/views/Transactions/__tests__/transactionMutation.test.jsx, frontend/src/views/Transactions/components/OrganizationList.jsx, frontend/src/views/Transactions/components/TransactionDetails.jsx, frontend/src/views/Transactions/components/__tests__/TransactionDetails.test.jsx, frontend/src/views/Transfers/AddEditViewTransfer.jsx, frontend/src/views/Transfers/components/TransferDetails.jsx, frontend/src/views/Transfers/components/TransferGraphic.jsx, frontend/src/views/Transfers/components/__tests__/AddPlainComment.test.jsx, frontend/src/views/Transfers/components/__tests__/AgreementDate.test.jsx, frontend/src/views/Transfers/components/__tests__/AttachmentList.test.jsx, frontend/src/views/Transfers/components/__tests__/CommentList.test.jsx, frontend/src/views/Transfers/components/__tests__/Comments.test.jsx, frontend/src/views/Transfers/components/__tests__/LabelBox.test.jsx, frontend/src/views/Transfers/components/__tests__/OrganizationBadge.test.jsx, frontend/src/views/Transfers/components/__tests__/Recommendation.test.jsx, frontend/src/views/Transfers/components/__tests__/SigningAuthority.test.jsx, frontend/src/views/Transfers/components/__tests__/TransferDetails.test.jsx, frontend/src/views/Transfers/components/__tests__/TransferGraphic.test.jsx
* Refactor useOrg into two files, one for org specific and one for all orgs requests
* Clean up imports and remove some console logs
* Add data loading to component and implement selector functionality
Closes: #871
=> feat: Hook up Orgs Card on IDIR Homepage

backend/lcfs/web/api/compliance_report/summary_service.py, frontend/package-lock.json, frontend/src/views/ComplianceReports/components/SummaryTable.jsx
- adds currency symbol for cells that are currency format
- adds the 'currency' format to line 11, closes #738
=> fix: currency dollar symbol line 11

frontend/cypress/e2e/Pages/User/UserCreation.feature, frontend/cypress/e2e/Pages/User/UserCreation.test.js, frontend/cypress/support/commands.js
This PR implements a Cypress E2E test for the user creation workflow.
Closes #305
=> Feat: Add Cypress E2E Test for User Creation Workflow - 305

backend/lcfs/web/api/compliance_report/summary_service.py, backend/lcfs/web/api/compliance_report/validation.py
- fix: remove unused import that was causing a circular import bug
- fix: line 19 calculation of fuel exports, closes #758 
note - currently negative cell values are displayed with a negative symbol. these negative values should be displayed as positive values with parenthesis. a ticket for this task is available and will be handled in that ticket: #934
=> fix: line 19 fuel export units display

frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx, frontend/src/views/OtherUses/AddEditOtherUses.jsx
* Also format FSE file
closes: #913
=> fix: Add stopEditingWhenCellsLoseFocus to compliance tables missing it

frontend/src/views/Transactions/_schema.js
=> feat: Change default sorting on Transactions to updateDate

etl/.gitignore, etl/docker-compose.yml, etl/nifi_scripts/fuel_code.groovy, etl/readme.md
* Rename Fuel_Code -> Fuel_Suffix to match DB
* Add git ignore for nifi log files
* Remove depreacted version from docker-compose
* Add extra instructions to readme
=> fix: Change Fuel Code -> Fuel Suffix for Fuel Code ETL

frontend/src/views/Transfers/AddEditViewTransfer.jsx, frontend/src/views/Transfers/__tests__/AddEditViewTransfer.test.jsx, frontend/src/views/Transfers/__tests__/_schema.test.js, frontend/src/views/Transfers/__tests__/buttonConfigs.test.jsx, frontend/src/views/Transfers/buttonConfigs.jsx, frontend/src/views/Transfers/components/Recommendation.jsx
- fixed bug on recommend button being clickable when recommendation not selected
- updated button visibility logic for directors
- tests
=> Fix: Transfer Button Logic Fixes - 921 929

backend/lcfs/web/api/compliance_report/constants.py, backend/lcfs/web/api/compliance_report/summary_service.py, backend/lcfs/web/api/transaction/repo.py, frontend/src/components/BCDataGrid/BCGridEditor.jsx, frontend/src/components/BCDataGrid/components/Editors/AsyncSuggestionEditor.jsx, frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/components/OrgDetailsCard.jsx, frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx, frontend/src/views/FinalSupplyEquipments/_schema.jsx
#849
fix for below
https://github.com/bcgov/lcfs/issues/849#issuecomment-2362347407
- Line 11 summary line fix
- line 17 fix https://github.com/bcgov/lcfs/issues/756#issuecomment-2349764800
=> Fix: FSE and summary lines fixes

backend/lcfs/web/api/compliance_report/schema.py, backend/lcfs/web/api/compliance_report/services.py, backend/lcfs/web/api/compliance_report/summary_service.py, backend/lcfs/web/api/compliance_report/views.py, backend/lcfs/web/api/final_supply_equipment/views.py, backend/lcfs/web/api/fuel_export/schema.py, backend/lcfs/web/api/fuel_export/views.py, frontend/src/views/NotionalTransfers/NotionalTransferSummary.jsx, frontend/src/views/OtherUses/OtherUsesSummary.jsx
* Only two tables with fixed widths, that forces them off the page at smaller screen size
* Update them to use translation file
* Fix Commmon -> Common *
=> fix: Remove fixed width of NotionalTransfer and OtherUses

frontend/src/constants/common.js, frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx, frontend/src/views/ComplianceReports/components/_schema.jsx
=> Feat: LCFS - Refine line 7 and 9 of the compliance report summary

frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx, frontend/src/views/ComplianceReports/components/_schema.jsx
This PR updates the input logic for Line 8 in the Compliance Report Summary based on specified criteria.
Closes #899
=> Feat: Update Line 8 Input Logic in Compliance Report - 899

frontend/package-lock.json
- serve-static and rollup version updates
=> Chore: package dependancy updates

backend/lcfs/db/seeders/dev/user_profile_seeder.py, backend/lcfs/db/seeders/dev/user_role_seeder.py
- Add Arturo Reyes Lopez as new developer in seed files.
=> Add new developer to seed files

frontend/src/views/ComplianceReports/components/_schema.jsx
=> Fix: LCFS - Refine line 7 and 9 of the compliance report summary #897

backend/lcfs/db/seeders/dev/admin_adjustment_history_seeder.py, backend/lcfs/db/seeders/dev_seeder.py, backend/lcfs/tests/user/test_user.py, backend/lcfs/web/api/user/repo.py, backend/lcfs/web/api/user/schema.py, backend/lcfs/web/api/user/services.py, backend/lcfs/web/api/user/views.py, backend/lcfs/web/exception/exceptions.py, frontend/src/assets/locales/en/admin.json, frontend/src/constants/routes/apiRoutes.js, frontend/src/views/Admin/AdminMenu/Menu.jsx, frontend/src/views/Admin/AdminMenu/components/UserActivity.jsx, frontend/src/views/Admin/AdminMenu/components/ViewUser.jsx, frontend/src/views/Admin/AdminMenu/components/__tests__/UserActivity.test.jsx, frontend/src/views/Admin/AdminMenu/components/_schema.js, frontend/src/views/Transactions/_schema.yup.js, frontend/src/views/Transfers/_schema.js, frontend/src/views/Transfers/components/TransferDetails.jsx
This PR adds the user activity table for both BCeID and IDIR users on the View User page.
It also includes improvements such as:
- Added admin adjustment history records on the 'dev' environment.
- Fixed validation error message for quantity and agreement date in the New Transfer page.
Closes #177
Closes #189
=> Feat: Add User Activity Table for BCeID and IDIR Users - 177, 189

frontend/src/views/Transfers/__tests__/AddEditViewTransfer.test.jsx, frontend/src/views/Transfers/__tests__/buttonConfigs.test.jsx, frontend/src/views/Transfers/components/AddPlainComment.jsx, frontend/src/views/Transfers/components/AttachmentList.jsx, frontend/src/views/Transfers/components/CommentList.jsx, frontend/src/views/Transfers/components/TransferDetails.jsx, frontend/src/views/Transfers/components/TransferHistory.jsx, frontend/src/views/Transfers/components/TransferSummary.jsx, frontend/src/views/Transfers/components/__tests__/AddPlainComment.test.jsx, frontend/src/views/Transfers/components/__tests__/AgreementDate.test.jsx, frontend/src/views/Transfers/components/__tests__/AttachmentList.test.jsx, frontend/src/views/Transfers/components/__tests__/CategoryCheckbox.test.jsx, frontend/src/views/Transfers/components/__tests__/CommentList.test.jsx, frontend/src/views/Transfers/components/__tests__/Comments.test.jsx, frontend/src/views/Transfers/components/__tests__/LabelBox.test.jsx, frontend/src/views/Transfers/components/__tests__/OrganizationBadge.test.jsx, frontend/src/views/Transfers/components/__tests__/Recommendation.test.jsx, frontend/src/views/Transfers/components/__tests__/SigningAuthority.test.jsx, frontend/src/views/Transfers/components/__tests__/TransferDetails.test.jsx, frontend/src/views/Transfers/components/__tests__/TransferDetailsCard.test.jsx, frontend/src/views/Transfers/components/__tests__/TransferHistory.test.jsx, frontend/src/views/Transfers/components/__tests__/TransferSummary.test.jsx, frontend/src/views/Transfers/components/__tests__/TransferView.test.jsx
This PR adds comprehensive UI unit tests for the transfer feature. Previously, there were 73 tests, and now there are 123 tests.
Closes #463
=> Feat: Add UI Unit Tests for Transfer Feature - 463

frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx, frontend/src/views/NotionalTransfers/NotionalTransferSummary.jsx, frontend/src/views/OtherUses/OtherUsesSummary.jsx
* Add flex to longer columns so they grow to expand the space instead of the grey bar at the end
* Remove debugger
=> fix: Auto-size text columns to keep nice grid size

backend/lcfs/tests/compliance_report/test_summary_service.py, backend/lcfs/web/api/compliance_report/summary_service.py
* Change to new requirement resulting in cleaner logic
* Add lots of tests
=> fix: Reset line 6/8 if line 4 changes

frontend/src/views/NotionalTransfers/AddEditNotionalTransfers.jsx, frontend/src/views/NotionalTransfers/_schema.jsx, frontend/src/views/OtherUses/AddEditOtherUses.jsx, frontend/src/views/OtherUses/_schema.jsx
* Also move config from memo to direct set since its constant
=> fix: Change NotionalTransfers and OtherUses to use fitGridWidth

frontend/src/views/ComplianceReports/components/SummaryTable.jsx
* Only use column.align for cells in summary table
=> fix: Change header cells to always center

backend/lcfs/web/api/fuel_code/repo.py
When users access a compliance report and view the allocation agreements details, the system currently displays all available fuel codes. Users have requested that the list be refined to display only the `active` fuel codes.
- Restrict Fuel Codes Display: The list of fuel codes shown to users now includes only active fuel codes, based on their effective_date and expiration_date.
The UI now filters out inactive or future fuel codes based on the effective_date and expiration_date.
Only fuel codes that are currently active are shown in the dropdown, providing a more relevant selection for users.
fuel_code_id|prefix_id|fuel_suffix|effective_date|expiration_date|
------------+---------+-----------+--------------+---------------+
7|        1|100.3      |    2024-10-01|     2024-10-09|
8| …
=> LCFS-969: fuel_code list based on effective_date and expiration_date

docker-compose.yml
* No is boolean but restart should be a string https://github.com/docker/compose/issues/3672
=> Fix Docker Compose

frontend/src/views/AllocationAgreements/AddAllocationAgreements.jsx, frontend/src/views/AllocationAgreements/_schema.jsx, frontend/src/views/FuelExports/AddEditFuelExports.jsx, frontend/src/views/FuelExports/_schema.jsx, frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx, frontend/src/views/FuelSupplies/_schema.jsx, frontend/src/views/NotionalTransfers/AddEditNotionalTransfers.jsx, frontend/src/views/NotionalTransfers/_schema.jsx, frontend/src/views/OtherUses/AddEditOtherUses.jsx, frontend/src/views/OtherUses/_schema.jsx
* Remove duplicate from everything other than FSE and Fuel Code tables
=> Remove duplicate from most tables

backend/lcfs/web/api/user/repo.py, backend/lcfs/web/api/user/services.py, backend/lcfs/web/core/decorators.py, frontend/src/utils/grid/cellRenderers.jsx
* Remove link so it no longer has a hover cursor
* Fix permission checks in backend to use correct user_roles
=> Remove Link from Status Renderer

backend/lcfs/web/api/transaction/repo.py, backend/lcfs/web/api/transaction/services.py, frontend/src/components/__tests__/RequireAuth.test.jsx
* Remove print
* Fix Type
* Remove broken tests
=> Small Fixes

backend/lcfs/conftest.py, backend/lcfs/tests/admin_adjustment/test_admin_adjustment.py, backend/lcfs/tests/compliance_report/test_compliance_report_views.py, backend/lcfs/tests/conftest.py, backend/lcfs/tests/fuel_code/test_fuel_code_views.py, backend/lcfs/tests/fuel_export/test_fuel_exports_views.py, backend/lcfs/tests/fuel_supply/test_fuel_supplies_view.py, backend/lcfs/tests/initiative_agreement/test_initiative_agreement_services.py, backend/lcfs/tests/initiative_agreement/test_initiative_agreement_view.py, backend/lcfs/tests/internal_comment/test_internal_comment.py, backend/lcfs/tests/organization/test_organization_views.py, backend/lcfs/tests/other_uses/test_other_uses_view.py, backend/lcfs/tests/test_access_control.py, backend/lcfs/tests/test_audit_events.py, backend/lcfs/tests/test_organization.py, backend/lcfs/tests/test_users.py, backend/lcfs/tests/transaction/test_transaction_views.py, backend/lcfs/tests/transfer/test_transfer_views.py, backend/lcfs/tests/user/test_user.py, backend/lcfs/web/api/initiative_agreement/services.py
* Fix mock user roles on initiative agreements
* Add an error message on director approval when roles do not match and only check for director role
* Disable auditing tests as auditing is not working, filed a ticket to fix
=> Small Test Fixes

backend/lcfs/tests/compliance_report/test_summary_service.py, backend/lcfs/web/api/compliance_report/summary_service.py
* Add code back to calculate total value and add to unit tests
* Add back line "" (total line) and update tests
=> fix: Add Total Line back + Fix Calc

backend/lcfs/web/api/base.py, backend/lcfs/web/api/compliance_report/repo.py, backend/lcfs/web/api/organization/services.py, backend/lcfs/web/api/transaction/repo.py, frontend/src/components/BCDataGrid/BCDataGridServer.jsx, frontend/src/themes/base/globals.js, frontend/src/utils/formatters.js, frontend/src/views/ComplianceReports/components/_schema.jsx, frontend/src/views/Transactions/_schema.js
- Filters in transaction table and compliance report are working propertly backend. 
- Inputs are not case sensitive, user can type lower or capital letters
- Date picker is added
- Configuration in the front end to allow filters, including special configuration for Enum values
- Add clear button to reset individual filters.
=> LCFS-985: Fixing filters in transaction and compliance report tables

frontend/src/views/Transfers/_schema.js, frontend/src/views/Transfers/components/Comments.jsx
- added validation to transfer comment fields for max length matching db values
=> Fix: Transfer Comment Inputs Validation

frontend/src/utils/formatters.js
Change in currencyFormatter affected to ComplianceReportSummary when passing a value in parameters. The issue was that the logic needs to take into consideration that transactions can have params.value with null value so this was displaying wrong information in the grid table.
This change is aimed to address the issue in ComplianceReportSummary while providing a solution for transactions.
=> hotfix-LCFS-985-BugsFiltersTransactionComplianceTable

.github/workflows/docker-auto-test.yaml, backend/lcfs/web/api/user/repo.py
> Grunert, Lindsy EMLI:EX:
> Easy fix?
> Hi Team. Looks like I can't switch my IDIR roles without getting this error:
> Anyone else see this error or is this a Lindsy thing?
> Let me know. Thank you!
Fix for above issue
=> fix: Role change issue fix

backend/lcfs/db/migrations/versions/2024-10-18-19-48_bb5504e743a0.py, backend/lcfs/db/models/transfer/Transfer.py, backend/lcfs/tests/transfer/test_transfer_repo.py, backend/lcfs/tests/transfer/test_transfer_services.py, backend/lcfs/tests/transfer/test_transfer_views.py, backend/lcfs/web/api/transfer/schema.py, frontend/cypress/e2e/Pages/Transfer/CreateTransferWithSigningAuth.feature, frontend/cypress/e2e/Pages/Transfer/CreateTransferWithTransfer.feature, frontend/cypress/e2e/Pages/Transfer/DirectorTransferFlow.feature, frontend/src/views/Transfers/__tests__/AddEditViewTransfer.test.jsx, frontend/src/views/Transfers/components/__tests__/TransferDetails.test.jsx
This PR updates the price per credit input box to support values with two decimal places in the credit proposal form.
Closes #996
=> Feat: Allow price per credit input to accept values with two decimal places - 996

frontend/src/views/Transactions/AddEditViewTransaction.jsx, frontend/src/views/Transactions/ViewOrgTransaction.jsx, frontend/src/views/Transactions/__tests__/AddEditViewTransaction.test.jsx, frontend/src/views/Transactions/buttonConfigs.jsx, frontend/src/views/Transactions/components/OrgTransactionDetails.jsx, frontend/src/views/Transactions/components/TransactionDetails.jsx, frontend/src/views/Transactions/components/__tests__/OrgTransactionDetails.test.jsx, frontend/src/views/Transactions/constants.js, frontend/src/views/Transactions/transactionMutation.js, frontend/src/views/Transfers/components/TransferView.jsx
* Move constants into constants file to remove circular dependencies from children importing the parents for the constants
=> fix: Circular Dependencies

frontend/src/hooks/useAdminAdjustment.js, frontend/src/hooks/useInitiativeAgreement.js
**Issue**
There are two imports that need update.
Getting the following error:
```
frontend  | Error:   Failed to scan for dependencies from entries:
frontend  |   /app/index.html
frontend  | /app/public/404.html
frontend  | /app/public/500.html
frontend  |
frontend  |   ✘ [ERROR] No matching export in "src/views/Transactions/AddEditViewTransaction.jsx" for import "ADMIN_ADJUSTMENT"
frontend  |
frontend  |     src/hooks/useAdminAdjustment.js:3:9:
frontend  |       3 │ import { ADMIN_ADJUSTMENT } from '@/views/Transactions/AddEditViewT...
frontend  |         ╵          ~~~~~~~~~~~~~~~~
frontend  |
frontend  |
frontend  | ✘ [ERROR] No matching export in "src/views/Transactions/AddEditViewTransaction.jsx" for import "INITIATIVE_AGREEMENT"
frontend  |
frontend  | …
```
=> Hotfix: Fixing errors when building frontend.

backend/lcfs/db/seeders/dev/fuel_code_seeder.py
- removed explicit fuel_code ids so auto sequencing could auto set them
=> fix: fuel code seeder sequencing

backend/lcfs/services/s3/client.py, backend/lcfs/settings.py
* We will be using the same buckets for multiple environments, so Kuan has asked that we accept a folder path env var
=> Add S3 Docs Path

backend/lcfs/db/seeders/dev/fuel_code_seeder.py
* Add 3 more fuel codes, so each fuel type (other than fossil-dreived) has at least one code
=> feat: Add More Fuel Codes

backend/lcfs/db/base.py, backend/lcfs/db/dependencies.py, backend/lcfs/tests/test_audit_events.py
* Store user in a context variable
* Use context var for update / create user
=> fix: Change audit columns to use default and onUpdate

backend/lcfs/tests/compliance_report/test_update_service.py, backend/lcfs/web/api/compliance_report/repo.py, backend/lcfs/web/api/compliance_report/summary_service.py, backend/lcfs/web/api/compliance_report/update_service.py
* The or check was causing the new reports 0 values to not be saved.
* Remove the or check since we should be passing in a fully calculate summary
=> fix: Do not copy previous summary values

backend/lcfs/db/migrations/versions/2024-10-18-19-46_a731a32947dc.py
* Migration is failing as it currently has floats/decimals
=> fix: Round Energy Column

frontend/src/views/Dashboard/components/cards/idir/DirectorReviewCard.jsx
This PR updates the director review widget filter to display compliance reports with a 'recommended by manager' status.
Closes #992
=> Fix: Adjust Director Review Widget Filter for 'Recommended by Manager' Status - 992

frontend/src/views/Transfers/components/TransferGraphic.jsx
This PR ensures that transfer decimal values display correctly in the graphic and persist after page refresh.
Closes #996
=> Fix: Enable Transfer Decimal Display and Persistence - 996

frontend/src/components/BCDataGrid/BCGridEditor.jsx
- feat: new param to enable add multi row, default false. closes #1111
=> feat: Schedule Add row functionality

backend/lcfs/conftest.py, backend/lcfs/tests/user/test_user.py, backend/lcfs/web/api/user/repo.py, backend/lcfs/web/api/user/schema.py, backend/lcfs/web/api/user/services.py, backend/lcfs/web/api/user/views.py, backend/lcfs/web/core/decorators.py, frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/assets/locales/en/admin.json, frontend/src/components/BCDataGrid/BCDataGridClient.jsx, frontend/src/components/BCDataGrid/BCDataGridEditor.jsx, frontend/src/components/BCDataGrid/BCDataGridEditorV2.jsx, frontend/src/components/BCDataGrid/BCDataGridServer.jsx, frontend/src/components/BCDataGrid/BCGridViewer.jsx, frontend/src/constants/routes/apiRoutes.js, frontend/src/constants/routes/routes.js, frontend/src/hooks/useUser.js, frontend/src/views/Admin/AdminMenu/Menu.jsx, frontend/src/views/Admin/AdminMenu/components/UserLoginHistory.jsx, frontend/src/views/Admin/AdminMenu/components/ViewUser.jsx, frontend/src/views/Admin/AdminMenu/components/__tests__/UserLoginHistory.test.jsx, frontend/src/views/Admin/AdminMenu/components/_schema.js, frontend/src/views/Admin/AdminMenu/index.js, frontend/src/views/Admin/__tests__/Menu.test.jsx, frontend/src/views/Users/UserActivity/UserActivity.jsx, frontend/src/views/Users/UserActivity/__tests__/UserActivity.test.jsx, frontend/src/views/Users/index.js
- #1035
- pytest issue with multipart package, so suppressing the warning message.
- added deprecated mark on BCDataGrid components, using jsdoc package.
- In BCDataGridViewer added reset button to clear caching of filter and sort applied on the grid, in case of error.
- Enclosed User activity component inside Role to prevent loading for unintended users.
- Removed unused code and components.
=> Feat: LCFS - Implement User Login History View for Administrators #1035

backend/lcfs/db/migrations/versions/2024-10-18-19-46_a731a32947dc.py, backend/lcfs/db/models/compliance/FuelSupply.py, backend/lcfs/settings.py
* Integer is not large enough to hold enough digits.
* Increase worker count to 2
=> fix: Change Energy to Big Int

backend/lcfs/db/migrations/versions/2024-10-24-16-17_413db49916b3.py
- Added uuid values in the versioning migration for existing Compliance reports, fuel supply, and fuel export records.
=> Fix: Add default uuid values for versioning fields

frontend/src/views/FuelSupplies/_schema.jsx
* Calculation is performed correctly on the backend, frontend just needs to show the field as it is.
=> fix: Remove frontend logic for ciOfFuel

frontend/src/views/Transactions/Transactions.jsx
This PR resolves a filtering issue for transactions in IDIR roles.
=> Fix: Fix Filtering and Default Organization View in Transactions

frontend/src/components/BCDataGrid/components/Editors/DateRangeCellEditor.jsx, frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx, frontend/src/views/FinalSupplyEquipments/_schema.jsx
**Fixes:**
- Enable Modal for Date Picker on Click: When the date field is clicked, a modal-based date picker now opens to allow the user selecting a date range.
- Fix Date Editing Functionality: Users can now enter and modify dates manually.
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=84737201&issue=bcgov%7Clcfs%7C1113)
=> LCFS-1113: BUG - FSE date range picker

backend/lcfs/logging_config.py, backend/lcfs/web/application.py, backend/lcfs/web/core/decorators.py
This PR refactors backend logging.
Changes include:
- Removing successful API logs to reduce log clutter
- Fixing `censor_sensitive_data_processor` for accurate data handling
- Removing unnecessary `audit_logging`
- Formatting Python code
=> Refactor: Enhance backend logging

backend/lcfs/tests/organization/test_organization_validation.py, backend/lcfs/tests/organization/test_organization_views.py
* Update for new supplemental fields
* Mock validation
=> fix: Fix remaining Org Tests

backend/lcfs/web/api/organization/views.py, frontend/src/hooks/useOrganization.js, frontend/src/views/ComplianceReports/components/NewComplianceReportButton.jsx, frontend/src/views/Organizations/ViewOrganization/ViewOrganization.jsx
issues w.r.t. BCeID users.
- Error loading https://lcfs-dev.apps.silver.devops.gov.bc.ca/organization
- reported years are pulled by hardcoding organization id as 1, hence causing 403 errors
- Error loading compliance reports.
=> LCFS Dev env. issues fix for BCeID user

backend/lcfs/services/keycloak/authentication.py, backend/lcfs/tests/test_auth_middleware.py, backend/lcfs/web/application.py
* Able to get some working but cannot figure out mocking AsyncContextManager
=> Update Auth Tests

backend/lcfs/tests/admin_adjustment/test_admin_adjustment.py, backend/lcfs/tests/organization/test_organization_views.py, backend/lcfs/tests/organizations/test_organizations_repo.py, backend/lcfs/tests/transaction/test_transaction_repo.py, backend/lcfs/tests/transfer/test_transfer_views.py, backend/lcfs/tests/user/test_user.py, backend/lcfs/web/api/user/views.py, backend/lcfs/web/core/decorators.py
* Fix various tests
* Small cleanup on shadowed var and orgId not being camel case
=> fix: Fix some tests

frontend/src/hooks/__tests__/useDashboard.test.jsx, frontend/src/views/Admin/__tests__/ViewUser.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/ComplianceReportSummary.test.jsx, frontend/src/views/Dashboard/components/cards/idir/__tests__/OrganizationsSummaryCard.test.jsx, frontend/src/views/Transactions/AddEditViewTransaction.jsx, frontend/src/views/Transactions/__tests__/transactionMutation.test.jsx, frontend/src/views/Transactions/components/__tests__/Comments.test.jsx, frontend/src/views/Transfers/AddEditViewTransfer.jsx, frontend/src/views/Transfers/components/__tests__/Comments.test.jsx, frontend/src/views/Transfers/components/__tests__/TransferView.test.jsx
- batch of tests that were skipped are now implemented
=> Fix: Updated frontend skipped tests

backend/lcfs/logging_config.py, backend/lcfs/web/core/decorators.py
This PR refactors backend logging to improve the readability of exception traces during development.
=> Refactor: Enhance Backend Logging for Exception Readability

backend/lcfs/web/api/fuel_supply/repo.py
* Was accidentally removed as part of adding versioning
=> fix: Add sorting back to Fuel Supply

frontend/src/views/ComplianceReports/components/_schema.jsx
* Remove all other logic for controlling the Diesel and Gasoline controls. Aim to remove this code and have it auto-load for 2025 and onwards.
=> fix: Always enable lines 7 and 9 in 2024

frontend/cypress/e2e/disclaimer_banner.cy.js, frontend/src/assets/locales/en/common.json
=> Remove reasons from disclaimer text

frontend/src/components/BCDataGrid/BCGridEditor.jsx, frontend/src/components/BCDataGrid/components/Editors/AsyncSuggestionEditor.jsx, frontend/src/components/BCDataGrid/components/Editors/AutocompleteCellEditor.jsx, frontend/src/components/BCDataGrid/components/Editors/DateRangeCellEditor.jsx, frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx, frontend/src/views/FinalSupplyEquipments/_schema.jsx
=> Fix: FSE date range & accessibility issues, focus issue in ag-grid.

frontend/src/views/Admin/AdminMenu/components/UserActivity.jsx, frontend/src/views/Admin/AdminMenu/components/__tests__/UserActivity.test.jsx
- Refactored user activity table to use new BCGridViewer
- Updated tests
=> Fix: User Activity Table - 1264

backend/lcfs/web/api/fuel_supply/repo.py, frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx
- fix: a bug that prevents new rows from saving if it is the same as a previously deleted row
- feat: end use is now a unique identifier for the row
closes #1216 
jsx file just a cleanup, no meaningful changes
=> Fix: FS duplicate bug #1216

backend/lcfs/web/api/fuel_code/repo.py
=> Fix: LCFS - BUG New fuel code pre-populated with 100.0 #1233

backend/lcfs/db/migrations/versions/2024-11-13-00-39_654858661ae7.py, backend/lcfs/tests/admin_adjustment/test_admin_adjustment.py, backend/lcfs/tests/user/test_user.py, backend/lcfs/web/api/user/services.py, frontend/src/assets/locales/en/common.json, frontend/src/hooks/useUser.js, frontend/src/views/Admin/AdminMenu/components/UserActivity.jsx
- #1236 - minor fixes.
- migration head fix
- failing test cases fix
- user activity missing react query
=> Fix: migration and asterisk header fix

backend/lcfs/db/migrations/versions/2024-11-22-18-20_3c07f891435d.py, backend/lcfs/db/models/compliance/ComplianceReport.py, backend/lcfs/db/models/fuel/FuelType.py, backend/lcfs/db/seeders/common/fuel_data_seeder.py, backend/lcfs/db/seeders/common/seed_fuel_data.json, backend/lcfs/tests/fuel_export/test_fuel_exports_actions_service.py, backend/lcfs/tests/fuel_supply/test_fuel_supplies_actions_service.py, backend/lcfs/web/api/fuel_code/schema.py, backend/lcfs/web/api/fuel_export/schema.py, backend/lcfs/web/api/fuel_supply/schema.py, backend/lcfs/web/api/other_uses/schema.py, frontend/src/assets/locales/en/fuelCode.json, frontend/src/views/FuelExports/_schema.jsx, frontend/src/views/FuelSupplies/_schema.jsx
* Update in seed scripts
* Write migration for DB
=> fix: Add superscripts for Units

frontend/src/views/Dashboard/components/cards/idir/OrganizationsSummaryCard.jsx
* Remove hard coded label, use organizations name
=> fix: Use set organizations name instead of label

etl/data-migration.sh
#1227
- wiki pages updated for usage details https://github.com/bcgov/lcfs/wiki/12.-Data-migration-from-TFRS-to-LCFS
=> Feat: LCFS - Migrate Data from TFRS to LCFS Production Using NIFI ETL Process with OpenShift Port Forwarding   #1227

backend/lcfs/services/s3/client.py
* Use request passed in instead of self.request which does not exist
=> Fix Wrong Request

backend/lcfs/services/s3/client.py, backend/lcfs/web/lifetime.py
Fix issues when uploading a document.
=> hotfix: Initialize S3 bucket in lifetime

frontend/src/assets/locales/en/fuelSupply.json, frontend/src/assets/locales/en/notionalTransfer.json, frontend/src/views/NotionalTransfers/_schema.jsx, frontend/src/views/OtherUses/_schema.jsx
This PR removes the Action column to reduce visual clutter and improve user experience.  
Closes #1282
=> Fix: Remove Action column - #1282

backend/poetry.lock, frontend/package-lock.json
=> Chore: Frontend package updates

backend/lcfs/services/tfrs/redis_balance.py, backend/lcfs/tests/services/tfrs/test_redis_balance.py
- additional fix on redis client init
=> Fix: missing redis instance fix

backend/lcfs/services/keycloak/authentication.py, backend/lcfs/web/lifetime.py
- Fixed auth cache for redis pool
- lifetime cache update
=> Fix: Jwk update for Redis Pool

backend/lcfs/tests/test_auth_middleware.py
- updated two main auth middleware tests after redis pool changes
=> Chore: Auth Middleware Tests

.gitignore, frontend/public/config/config.js, frontend/src/constants/config.js, frontend/src/utils/__tests__/withFeatureFlag.test.jsx, frontend/src/utils/__tests__/withRole.test.jsx, frontend/src/utils/withFeatureFlag.jsx, frontend/src/views/ComplianceReports/components/AssessmentCard.jsx, frontend/src/views/Notifications/Notifications.jsx
* Update config with new feature flags
* Add new helper function for checking if one is enabled
* Follow the withRole pattern to add a withFeatureFlag HOC
=> feat: Add front end feature flags

backend/lcfs/db/seeders/common/seed_fuel_data.json, frontend/src/views/FuelExports/_schema.jsx, frontend/src/views/FuelSupplies/_schema.jsx
- feat: added new options to the end use type options
- chore: organize IDs so they start at 1 and are sequential
- fix: increase width of end use type column
=> Feat: end use type options

backend/lcfs/web/api/fuel_code/repo.py, frontend/src/components/BCDataGrid/components/Editors/DateEditor.jsx, frontend/src/components/BCDataGrid/components/Filters/BCColumnSetFilter.jsx, frontend/src/main.jsx, frontend/src/views/Admin/AdminMenu/components/_schema.js, frontend/src/views/ComplianceReports/components/_schema.jsx, frontend/src/views/FuelCodes/_schema.jsx, frontend/src/views/Organizations/ViewOrganization/_schema.js
* Set max year to 2400 so it limits the input to 4 numbers
* Hoist localization provider to app level so we only have one and set it to use dayjs
* Delete suppressFloatingFilterButton, I was unable to find this anywhere so I believe it does nothing
=> fix: Add max year to date filters

backend/lcfs/db/migrations/versions/2024-12-05-02-20_d4104af84f2b.py, backend/lcfs/db/migrations/versions/2024-12-06-01-23_26ab15f8ab18.py
- feat: migration for end use type table row updates, #1175
=> feat: migration for end use types + migration fix

frontend/cypress/e2e/Pages/ComplianceReport/ComplianceReport.test.js, frontend/cypress/e2e/Pages/ComplianceReport/ComplianceReportManagement.feature, frontend/src/views/ComplianceReports/components/ActivityLinkList.jsx, frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx, frontend/src/views/ComplianceReports/components/SummaryTable.jsx
* Expand existing cypress test to enter an FS and confirm the values show in the compliance report summary
=> feat: Add Cypress test for entering FS

frontend/src/main.jsx, frontend/src/views/FuelCodes/_schema.jsx
* Remove filters from fuel code date columns
* Change back to previous adapter functions that dont cause issues
=> fix: Remove filtering on Date Columns

frontend/cypress/e2e/Pages/ComplianceReport/ComplianceReport.test.js, frontend/cypress/e2e/Pages/ComplianceReport/ComplianceReportManagement.feature, frontend/cypress/e2e/Pages/User/UserCreation.test.js, frontend/cypress/e2e/accessibility.cy.js, frontend/cypress/e2e/add__edit_org.cy.js, frontend/cypress/e2e/disclaimer_banner.cy.js, frontend/cypress/e2e/organization.cy.js, frontend/cypress/e2e/user_flow.cy.js
* Now include checking rounding on line 6, submitting the report, and checking the IDIR can see it
=> feat: Expand Compliance Report Test

.github/workflows/docker-auto-test.yaml
- updated docker-auto-test with separate jobs for frontend and backend tests
=> Chore: Parallel Test Workflow

backend/lcfs/tests/compliance_report/test_update_service.py, backend/lcfs/tests/initiative_agreement/test_initiative_agreement_services.py, backend/lcfs/tests/transfer/test_transfer_services.py, frontend/src/components/BCDataGrid/BCGridBase.jsx, frontend/src/views/Notifications/NotificationMenu/components/Notifications.jsx
updating code as per new migration: https://www.ag-grid.com/react-data-grid/row-selection/
=> bug fix for ag-grid checkbox

frontend/src/views/AllocationAgreements/AllocationAgreementSummary.jsx, frontend/src/views/ComplianceReports/components/ReportDetails.jsx, frontend/src/views/FinalSupplyEquipments/FinalSupplyEquipmentSummary.jsx, frontend/src/views/FuelExports/FuelExportSummary.jsx, frontend/src/views/FuelSupplies/FuelSupplySummary.jsx, frontend/src/views/NotionalTransfers/NotionalTransferSummary.jsx, frontend/src/views/OtherUses/OtherUsesSummary.jsx
* Only execute navigate if report is in Draft status to prevent draft clicks from going to edit
=> fix: Disable navigating unless report is draft

backend/lcfs/services/rabbitmq/report_consumer.py, backend/lcfs/tests/services/rabbitmq/test_report_consumer.py, backend/lcfs/web/api/compliance_report/services.py
- updated syncing logic for supplemental report creation
=> Feat: Supplemental Report Syncing

frontend/src/utils/grid/cellRenderers.jsx, frontend/src/views/Admin/AdminMenu/components/UserLoginHistory.jsx, frontend/src/views/Admin/AdminMenu/components/_schema.js
* Use new renderer with pill style instead of checkboxes
* Minor fixes to User Login Table, using ID as string and removing invalid cell data types.
=> feat: Add nice renderer for login status

backend/lcfs/db/migrations/versions/2025-01-06-19-01_94306eca5261.py, backend/lcfs/db/models/fuel/ProvisionOfTheAct.py, backend/lcfs/web/api/allocation_agreement/repo.py, backend/lcfs/web/api/fuel_export/repo.py, backend/lcfs/web/api/fuel_supply/repo.py, backend/lcfs/web/api/other_uses/repo.py
* Add is_legacy to provisons and follow similar logic to fuel types
* Copy over legacy provisions from TFRS -> LCFS
=> feat: Add Legacy Provisions

frontend/src/components/BCDataGrid/components/Filters/BCDateFloatingFilter.jsx
* Date filter is not settings its initial value on load
* Check dateFrom the field we use to see if its valid instead of one we don't
=> fix: Check dateFrom instead of filter

frontend/src/layouts/MainLayout/components/SupplierBalance.jsx, frontend/src/views/Dashboard/components/cards/bceid/OrgBalanceCard.jsx, frontend/src/views/Dashboard/components/cards/idir/OrganizationsSummaryCard.jsx, frontend/src/views/Dashboard/components/cards/idir/__tests__/OrganizationsSummaryCard.test.jsx, frontend/src/views/Organizations/ViewOrganization/_schema.js, frontend/src/views/Transactions/components/OrganizationList.jsx, frontend/src/views/Transfers/components/OrganizationBadge.jsx, frontend/src/views/Transfers/components/__tests__/OrganizationBadge.test.jsx
This reverts commit d8f7b522051d2d88952e42e35a6160494389b2ff.
=> Revert "fix: Subtract reserve from credit balance"

frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx, frontend/src/views/FuelSupplies/_schema.jsx
=> fix: for compliance report schedules text

frontend/src/components/BCDataGrid/BCGridViewer.jsx
caused by infinite looping in the useeffect
=> fix: fixes front end test  hang

frontend/package-lock.json, frontend/package.json, frontend/src/views/FinalSupplyEquipments/_schema.jsx, frontend/src/views/Transfers/components/TransferHistory.jsx
* Use custom fn as dayjs has no way to display timezones
* Try and remove moment
=> fix: Change Transaction history to full timestamp

backend/lcfs/web/api/organizations/repo.py, backend/lcfs/web/api/organizations/services.py, frontend/src/layouts/MainLayout/components/HeaderComponent.jsx, frontend/src/layouts/MainLayout/components/UserProfileActions.jsx
Fix #1716
- Add links to organization and user_name to redirect to profile page.
=> Fix: LCFS - Download Organization Information in PROD needs balances input #1716

frontend/src/views/ComplianceReports/components/OrganizationAddress.jsx
This PR updates the bullet list style and alignment for organization information to maintain consistency.
Closes #1772
=> Fix: Bullet list style and alignment - 1772

backend/lcfs/db/migrations/versions/2025-01-20-14-40_ec826b9226df.py
- updated business logic and clean up in seeder migration
=> Fix: seeder migration updated

frontend/src/views/ComplianceReports/components/AssessmentCard.jsx
=> Fix: LCFS - BUG - Organization details Edit button #1781

frontend/src/components/BCNavbar/index.jsx, frontend/src/components/BCWidgetCard/BCWidgetCard.jsx, frontend/src/layouts/MainLayout/MainLayout.jsx, frontend/src/views/Dashboard/components/cards/bceid/FeedbackCard.jsx, frontend/src/views/Dashboard/components/cards/bceid/OrgBalanceCard.jsx, frontend/src/views/Dashboard/components/cards/bceid/OrgDetailsCard.jsx, frontend/src/views/Dashboard/components/cards/bceid/OrgTransactionsCard.jsx, frontend/src/views/Dashboard/components/cards/bceid/OrgUserSettingsCard.jsx, frontend/src/views/Dashboard/components/cards/bceid/WebsiteCard.jsx, frontend/src/views/Dashboard/components/cards/idir/AdminLinksCard.jsx, frontend/src/views/Dashboard/components/cards/idir/OrganizationsSummaryCard.jsx, frontend/src/views/Dashboard/components/cards/idir/UserSettingsCard.jsx, frontend/src/views/Notifications/NotificationMenu/components/NotificationSettingsForm.jsx
=> fix: cypress accessibility issues

backend/lcfs/web/api/user/views.py, frontend/src/components/BCDataGrid/BCDataGridServer.jsx, frontend/src/views/Admin/AdminMenu/components/Users.jsx, frontend/src/views/Admin/AdminMenu/components/_schema.js
- fix: filter reset clearing defaults, closes #1775
=> fix: default filter on filter reset

frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/components/AssessmentCard.jsx, frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx, frontend/src/views/ComplianceReports/components/__tests__/AssessmentCard.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/ComplianceReportSummary.test.jsx
* They can be met/not met independently, so use two variables
* Fix logic to check specific lines instead of the totals, as reserve credits do not count towards met / not met
=> fix: Separate hasMet into two variables

frontend/src/utils/schedules.js, frontend/src/views/AllocationAgreements/AddEditAllocationAgreements.jsx, frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx, frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx, frontend/src/views/FuelExports/AddEditFuelExports.jsx, frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx, frontend/src/views/NotionalTransfers/AddEditNotionalTransfers.jsx, frontend/src/views/OtherUses/AddEditOtherUses.jsx
* Move all schedule logic to a standard function
* Add logic to standard function to re-create a default row when the last row is deleted
=> feat: Standardize Deletion Logic

frontend/src/components/BCDataGrid/BCGridBase.jsx
* Close all selects on scroll start, no need to be clever
=> fix: Close select on grid scroll

backend/lcfs/tests/other_uses/test_other_uses_view.py, backend/lcfs/web/api/allocation_agreement/schema.py, backend/lcfs/web/api/allocation_agreement/services.py, backend/lcfs/web/api/allocation_agreement/views.py, backend/lcfs/web/api/fuel_supply/repo.py, frontend/src/utils/grid/cellRenderers.jsx, frontend/src/views/AllocationAgreements/AddEditAllocationAgreements.jsx, frontend/src/views/AllocationAgreements/_schema.jsx, frontend/src/views/FuelCodes/AddFuelCode/AddEditFuelCode.jsx, frontend/src/views/FuelCodes/AddFuelCode/_schema.jsx, frontend/src/views/FuelCodes/_schema.jsx
=> Fix: LCFS - BUG - Inconsistent Dropdown List for Approved Fuel Codes in Compliance Reporting Schedules #1800

backend/lcfs/web/api/compliance_report/summary_service.py, frontend/src/views/Dashboard/components/cards/bceid/OrgUserSettingsCard.jsx, frontend/src/views/Dashboard/components/cards/bceid/__tests__/OrgUserSettingsCard.test.jsx, frontend/src/views/Dashboard/components/cards/idir/UserSettingsCard.jsx, frontend/src/views/Dashboard/components/cards/idir/__tests__/UserSettingsCard.test.jsx, frontend/src/views/Transactions/Transactions.jsx
* Skip ratio column in summary so we only have a single line 21
* Remove dead help links from Cards
* Give buttons a bit more room on transactions page to prevent them from squishing
=> fix: Various Bug Fixes

backend/lcfs/tests/other_uses/test_other_uses_repo.py, backend/lcfs/web/api/other_uses/repo.py
Missed out fix for Other uses.
Fixes: #1800
=> Fix: LCFS - BUG - Inconsistent Dropdown List for Approved Fuel Codes in Compliance Reporting Schedules

frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx, frontend/src/views/ComplianceReports/components/__tests__/ComplianceReportSummary.test.jsx
* It should be checking the summary penalty amount not the amounts in the report
=> fix: Update met/not met logic

backend/lcfs/db/migrations/versions/2025-01-20-14-20_32d9a649c8aa.py, backend/lcfs/db/migrations/versions/2025-01-31-10-48_d4f91d033ac7.py, backend/lcfs/db/models/compliance/ComplianceReportStatus.py, frontend/src/utils/grid/cellRenderers.jsx, frontend/src/views/ComplianceReports/components/_schema.jsx
- Add historical rejected status for display purposed
=> Feat: Add Historical Rejected Status

frontend/src/constants/common.js, frontend/src/views/Dashboard/components/cards/bceid/OrgUserSettingsCard.jsx, frontend/src/views/Dashboard/components/cards/idir/UserSettingsCard.jsx
* Add constant for help guide URL
=> feat: Add Help Links to Settings Cards

backend/lcfs/web/api/compliance_report/repo.py, backend/lcfs/web/api/compliance_report/services.py, backend/lcfs/web/api/compliance_report/views.py, frontend/src/views/ComplianceReports/components/_schema.jsx
* Pass in request.user instead of trying to read it from self
* The FE for Compliance Report was updated to show nickname in the Type column but the filter was not updated
=> fix: 2 Bug Fixes

backend/lcfs/db/models/compliance/ComplianceReportSummary.py
=> Fix: CR Summary Version fix

frontend/src/views/Users/AddEditUser/AddEditUser.jsx, frontend/src/views/Users/AddEditUser/__tests__/AddEditUser.test.jsx, frontend/src/views/Users/AddEditUser/_schema.js
=> Feat: LCFS - Make "Job Title" Field Optional in Add/Edit BCeID User Page #1909

backend/lcfs/tests/compliance_report/test_summary_service.py, backend/lcfs/web/api/compliance_report/summary_service.py
- Added missing uci value into summary compliance units calculation
=> Fix: UCI Summary Calculation - 1943

frontend/src/assets/locales/en/common.json, frontend/src/components/Unauthorized.jsx
Add a "Return to Login" button to the Unauthorized page for easier navigation.
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=95894960&issue=bcgov%7Clcfs%7C1874)
=> LCFS-1874: Unauthorized Access Redirecting to Login

backend/lcfs/web/api/email/services.py
- update email service to pass on failures instead of breaking report and transfer submissions
=> Fix: Allows passthrough on email failure

frontend/src/services/useApiService.js
- We only want to show toast notifications in the dev environment
=> Chore: Updated toast config

frontend/public/config/config.js, frontend/src/constants/config.js, frontend/src/views/ComplianceReports/ViewLegacyComplianceReport.jsx
* Remove no longer used notification flag
* Default to true on localhost
=> feat: Feature Flag Legacy Details

backend/lcfs/utils/spreadsheet_builder.py, backend/lcfs/web/api/final_supply_equipment/export.py, backend/lcfs/web/api/final_supply_equipment/repo.py, backend/lcfs/web/api/final_supply_equipment/services.py
* Write a second sheet of valid values instead of using formula values directly
* List formulas do not allow special characters nor do they support escaping
* This new approach does double the XLSX size but allows any values in the selects (such as comma)
=> fix: New Excel Validation Approach

frontend/src/hooks/useTransactions.js, frontend/src/views/Transactions/components/OrganizationList.jsx
* Was filtered out before, we now want to allow it
* Backend is still correctly filtering who can see what
=> feat: Add DRAFT back to IDIR filter options

backend/lcfs/db/migrations/versions/2025-02-12-11-01_9e1da9e38f20.py, backend/lcfs/db/migrations/versions/2025-02-12-18-16_9e1da9e38f20.py, backend/lcfs/db/models/compliance/CompliancePeriod.py, backend/lcfs/db/models/fuel/EnergyDensity.py, backend/lcfs/db/models/fuel/EnergyEffectivenessRatio.py, backend/lcfs/tests/fuel_code/test_fuel_code_repo.py, backend/lcfs/web/api/fuel_code/repo.py, backend/lcfs/web/api/fuel_export/repo.py, backend/lcfs/web/api/fuel_supply/repo.py
- Add data for energy density and EER for the previous compliance periods
- Add compliance period lookups for energy density and EER.
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=96871218&issue=bcgov%7Clcfs%7C1938)
=> LCFS-1938: Refactor EnergyDensity and EnergyEffectivenessRatio for Annual Values and Backfill Data

frontend/package-lock.json, frontend/package.json
- updated esbuild and package-lock.json
=> Chore: Update Packages

frontend/src/views/FuelExports/AddEditFuelExports.jsx
* ID is required for proper versioning
=> fix: Set complianceReportId on Exports

backend/lcfs/web/api/transfer/services.py
=> Fix: LCFS - BUG Government user able to use the URL transfer ID to view a transfer in "sent" status #2038

frontend/src/components/BCDataGrid/BCGridEditor.jsx
* Remove functions that don't exist
* Use api instead of gridApi
=> fix: Grid API Calls

frontend/src/components/KeycloakProvider.jsx, frontend/src/utils/__tests__/keycloak.test.js, frontend/src/utils/keycloak.js
=> Fix: LCFS - Assess and Fix Inconsistent Auth Token Auto-Refresh #2021

backend/lcfs/web/api/notional_transfer/views.py
- missing request.user param added to notional transfers paginated method
=> Fix: Notional Transfers Method Param - 2073

backend/lcfs/db/migrations/versions/2025-02-12-18-15_0d5836bb1bf8.py
- subqueries in materialized view were returning more than one result
=> HotFix: limit added to materialized view subqueries

backend/lcfs/web/api/fuel_export/repo.py, frontend/src/views/FuelExports/AddEditFuelExports.jsx
- Sorted by create_date
- Autopopulate End Use when only one value is avaiable.
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=99187276&issue=bcgov%7Clcfs%7C2083)
=> LCFS-2083: BUG - Export fuel schedule sorting

backend/lcfs/tests/fuel_export/test_fuel_exports_repo.py, backend/lcfs/web/api/final_supply_equipment/__init__.py, backend/lcfs/web/api/fuel_export/__init__.py, backend/lcfs/web/api/fuel_export/repo.py, backend/lcfs/web/api/fuel_supply/repo.py, backend/lcfs/web/api/notional_transfer/repo.py, backend/lcfs/web/api/other_uses/repo.py
- Implemented and verified delete actions for Notional Transfer, Allocation Agreement, Fuel Export, Fuel Supply, Other Use, and Final Supply Equipment schedules.
=> Feat: Delete Actions for Schedules

backend/lcfs/tests/fuel_code/test_fuel_code_exporter.py, backend/lcfs/web/api/fuel_code/export.py
Tested with 2,300 and worked great.
=> fix: Bump Fuel Code Limit to 10,000

backend/lcfs/tests/fuel_code/test_fuel_code_repo.py, backend/lcfs/web/api/fuel_code/repo.py, frontend/package-lock.json, frontend/src/views/ComplianceReports/components/NewComplianceReportButton.jsx
- updated package-lock
- fuel code default suffix logic updated for proxy 001 values
- fixed width of compliance report year dropdown
=> Fix: Fuel Code Default Value, UI Fixes - 2160 2076

backend/lcfs/db/migrations/versions/2025-02-26-14-53_173179aeed95.py, backend/lcfs/db/migrations/versions/2025-03-05-14-00_173179aeed95.py, backend/lcfs/db/models/compliance/AllocationAgreement.py, backend/lcfs/tests/allocation_agreement/conftest.py, backend/lcfs/tests/allocation_agreement/test_alllocation_agreement_repo.py, backend/lcfs/tests/allocation_agreement/test_allocation_agreement_services.py, backend/lcfs/tests/allocation_agreement/test_allocation_agreement_views.py, backend/lcfs/web/api/allocation_agreement/repo.py, backend/lcfs/web/api/allocation_agreement/schema.py, backend/lcfs/web/api/allocation_agreement/services.py, backend/lcfs/web/api/allocation_agreement/views.py, backend/lcfs/web/api/compliance_report/services.py, backend/lcfs/web/api/compliance_report/views.py, frontend/src/constants/routes/apiRoutes.js, frontend/src/routes/routeConfig/reportRoutes.jsx, frontend/src/routes/routes.js, frontend/src/views/AllocationAgreements/AddEditAllocationAgreements.jsx, frontend/src/views/AllocationAgreements/AllocationAgreementChangelog.jsx, frontend/src/views/AllocationAgreements/_schema.jsx, frontend/src/views/ComplianceReports/components/ReportDetails.jsx
Versioning for allocation agreement:
Edit:
Add:
Delete:
[Story](https://github.com/orgs/bcgov/projects/137/views/1?filterQuery=arey&pane=issue&itemId=97853319&issue=bcgov%7Clcfs%7C2005)
=> LCFS-2005:  Implement Versioning for Allocation Agreement and Update Supporting Services

frontend/src/views/Transactions/Transactions.jsx, frontend/src/views/Transactions/components/OrganizationList.jsx
Include unregistered organizations to the dropdown list for IDIR users.
[Story](https://github.com/orgs/bcgov/projects/137/views/1?filterQuery=arey&pane=issue&itemId=99427971&issue=bcgov%7Clcfs%7C2104)
=> LCFS-2104:  Organization filter on the IDIR Transaction page

frontend/src/views/AllocationAgreements/AddEditAllocationAgreements.jsx, frontend/src/views/AllocationAgreements/__tests__/AddEditAllocationAgreements.test.jsx, frontend/src/views/AllocationAgreements/_schema.jsx, frontend/src/views/Users/AddEditUser/__tests__/AddEditUser.test.jsx
Missing logic in Allocation Agreement when suplemental report is in Draft:
=> Added missing changelog logic to AddEditAllocationAgreements

backend/lcfs/tests/allocation_agreement/test_alllocation_agreement_repo.py, backend/lcfs/web/api/allocation_agreement/repo.py, backend/lcfs/web/api/compliance_report/export.py
* Update export code with updates to service layers get_effective
* Fix enum being compared to not enum
* Change get allocation agreement to return schemas instead of flat dicts
=> fix: Export Fixes

backend/lcfs/web/api/email/services.py, backend/lcfs/web/api/email/templates/notification_base.html
This PR includes the following fixes:
- Investigated and resolved the issue preventing email notifications for IDIR users.
- Added logging for better debugging in production.
Closes #2196
=> Fix: Resolve Email Notifications Issue for IDIR Users in PROD - 2196

frontend/src/views/Organizations/AddEditOrg/__tests__/AddEditOrgForm.test.jsx, frontend/src/views/Organizations/AddEditOrg/__tests__/_schema.test.js, frontend/src/views/Organizations/Organizations.jsx, frontend/src/views/Organizations/ViewOrganization/ViewOrganization.jsx, frontend/src/views/Organizations/ViewOrganization/__tests__/ViewOrganization.test.jsx, frontend/src/views/Organizations/ViewOrganization/__tests__/_schema.test.js, frontend/src/views/Organizations/__tests__/Organizations.test.jsx
Add test coverage for Organizations
=> LCFS-2023: Add Test Coverage for Organizations Frontend

backend/lcfs/services/s3/schema.py, backend/lcfs/tests/document/test_document_view.py, backend/lcfs/web/api/compliance_report/update_service.py, backend/lcfs/web/api/compliance_report/views.py, backend/lcfs/web/api/document/views.py, backend/lcfs/web/api/initiative_agreement/validation.py, backend/lcfs/web/api/organization/views.py, frontend/src/components/Documents/DocumentTable.jsx, frontend/src/components/Documents/__test__/DocumentUploadDialog.test.jsx, frontend/src/hooks/useDocuments.js, frontend/src/views/SupportingDocuments/SupportingDocumentSummary.jsx, frontend/src/views/Transactions/components/OrgTransactionDetails.jsx, frontend/src/views/Transactions/components/TransactionView.jsx
* Change from inline -> download so we can specify the file name
* Add access checks for each of the current file types
* Add tests
=> feat: Change documents to download

frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx, frontend/src/views/ComplianceReports/components/OrganizationAddress.jsx, frontend/src/views/ComplianceReports/components/__tests__/OrganizationAddress.test.jsx
- Updated address logic so that serviceAddress is now the only required address in the compliance report view
- Updated test
=> Feat: Updated CR Address Requirements

frontend/src/hooks/useRole.js, frontend/src/views/Admin/AdminMenu/components/RoleSelectFloatingFilter.jsx, frontend/src/views/Admin/AdminMenu/components/_schema.js
- Created wrapper component for role filter to fix react query caching issue with role dropdown options.
=> Fix: Role Dropdown Filter - 2188

frontend/src/components/BCDataGrid/components/Editors/DateEditor.jsx, frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx, frontend/src/views/FinalSupplyEquipments/__tests__/AddEditFinalSupplyEquipments.test.jsx, frontend/src/views/FinalSupplyEquipments/__tests__/schema.test.jsx, frontend/src/views/FinalSupplyEquipments/_schema.jsx
- Removed date range picker in favour of two date columns
- Added FSE tests
=> Feat: FSE Date Columns Refactor - 2184

frontend/package-lock.json, frontend/src/views/ComplianceReports/__tests__/EditViewComplianceReports.test.jsx, frontend/src/views/ComplianceReports/components/ActivityLinksList.jsx, frontend/src/views/ComplianceReports/components/ActivityListCard.jsx, frontend/src/views/ComplianceReports/components/__tests__/ActivityLinksList.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/ActivityListCard.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/HistoryCard.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/Introduction.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/LegacyAssessmentCard.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/NewComplianceReportButton.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/OrgDetailsCard.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/ReportDetails.test.jsx
- frontend tests for component coverage
- package-lock.json update
=> Feat: Compliance Reports Tests - 2072

backend/lcfs/db/migrations/versions/2025-03-17-20-44_e77de76bb555.py, backend/lcfs/db/models/organization/Organization.py, backend/lcfs/db/models/organization/OrganizationAddress.py, backend/lcfs/db/models/organization/OrganizationAttorneyAddress.py, backend/lcfs/web/api/organizations/repo.py, backend/lcfs/web/api/organizations/services.py, backend/lcfs/web/api/organizations/views.py
* Missing FK for both addresses on Org
* Delete dead links
* Fix logic to be able to create new ones
=> fix: Delete Dead Records

frontend/src/views/FuelExports/_schema.jsx
* Don't try and use complex front end logic, rely on backend value to be correct
Fixes: #2251
=> fix: Rely on backend

frontend/src/hooks/useComplianceReports.js
Bug fix: #2205
https://github.com/bcgov/lcfs/issues/2205#issuecomment-2734823888
=> Fix: To clear caching from react queries upon supplemental report delete

frontend/src/assets/locales/en/common.json, frontend/src/assets/locales/en/reports.json, frontend/src/components/InternalComments/index.jsx, frontend/src/components/TogglePanel.jsx, frontend/src/constants/routes/routes.js, frontend/src/routes/routeConfig/reportRoutes.jsx, frontend/src/routes/routes.js, frontend/src/themes/components/iconButton.js, frontend/src/views/AllocationAgreements/AllocationAgreementChangelog.jsx, frontend/src/views/CompareReports/CompareReports.jsx, frontend/src/views/CompareReports/__tests__/CompareReports.test.jsx, frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/buttonConfigs.jsx, frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx, frontend/src/views/ComplianceReports/components/ReportDetails.jsx, frontend/src/views/ComplianceReports/components/__tests__/ComplianceReportSummary.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/ReportDetails.test.jsx, frontend/src/views/FuelExports/FuelExportChangelog.jsx, frontend/src/views/FuelSupplies/FuelSupplyChangelog.jsx, frontend/src/views/NotionalTransfers/NotionalTransferChangelog.jsx, frontend/src/views/OtherUses/OtherUsesChangelog.jsx
* Add new toggle component
* Use toggle to switch between summary and change log
* Add hover back to edit icons
=> feat: Add Togglable Changelogs

backend/lcfs/db/migrations/versions/2025-03-17-10-38_ac0ac5d0c81b.py, backend/lcfs/db/migrations/versions/2025-03-25-15-38_ac0ac5d0c81b.py, etl/geocode_locations.sh
This update introduces latitude and longitude for fuel codes associated with fuel production facilities.
In Metabase, Where is this fuel coming from? (will need to use fuel code production facility information)
Added a location table to store unique records for production facilities.
Ensured unique entries to prevent duplicate location data.
Allow fuel production facility locations to be visualized on Metabase maps.
=> LCFS-2169: Metabase - Renewable fuel requirement queries/dashboards

frontend/src/views/FuelExports/_schema.jsx, frontend/src/views/FuelSupplies/_schema.jsx
* Fixes incorrect front-end lookup
Fixes: #2300
=> fix: Use backend values for Energy Density

backend/lcfs/tests/compliance_report/test_compliance_report_repo.py, backend/lcfs/tests/compliance_report/test_compliance_report_services.py, backend/lcfs/web/api/compliance_report/repo.py, backend/lcfs/web/api/compliance_report/services.py, backend/lcfs/web/api/compliance_report/views.py, backend/lcfs/web/api/organization/views.py, frontend/src/assets/locales/en/reports.json, frontend/src/constants/routes/apiRoutes.js, frontend/src/hooks/useComplianceReports.js, frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/buttonConfigs.jsx
=> Feat: LCFS - Allow the IDIR analyst to delete a draft Government adjustment or Reassessment #2206

bcgovpubcode.yml
As per:  https://github.com/bcgov/pubcode/wiki/Frequently-Asked-Questions
=> feat: Initial Pub Code Commit

frontend/package-lock.json, frontend/package.json, frontend/src/views/ComplianceReports/buttonConfigs.jsx
Fix #2343
Native Date function has no support for time zone, hence added luxon library to accurately calculate time.
=> Hotfix: LCFS - Return report to the supplier cut off #2343

backend/lcfs/web/api/compliance_report/export.py, backend/lcfs/web/api/compliance_report/schema.py
=> Fix: LCFS - Compliance report Excel download refinement #2272

backend/lcfs/web/api/compliance_report/services.py
=> Fix: LCFS - BUG - Draft information in history #2314

frontend/src/hooks/useAllocationAgreement.js, frontend/src/views/AllocationAgreements/AddEditAllocationAgreements.jsx, frontend/src/views/AllocationAgreements/AllocationAgreementSummary.jsx, frontend/src/views/AllocationAgreements/__tests__/AddEditAllocationAgreements.test.jsx, frontend/src/views/ComplianceReports/components/ReportDetails.jsx, frontend/src/views/ComplianceReports/components/__tests__/ReportDetails.test.jsx
* Only summary left using data grid server
=> feat: Move allocation agreements to BCGridViewer

backend/lcfs/web/api/compliance_report/services.py
- Fixed logic for Government adjustments to use address from the previous report
Closes #2221
=> Fix: Load address from previous report in Gov Adjustments - 2221

frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx, frontend/src/views/FuelSupplies/_schema.jsx
* Remove fuel supply mapping again
=> fix: Fuel Supply Fixes

frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx
* Clear saved filters when submitting a report
=> feat: Clear filters before redirecting to Compliance Reports

backend/lcfs/db/migrations/versions/2025-04-03-18-15_0d5836cb1bf8.py, backend/lcfs/db/models/transaction/TransactionView.py, backend/lcfs/tests/transaction/test_transaction_services.py, backend/lcfs/tests/transaction/transaction_payloads.py, backend/lcfs/tests/transfer/test_transfer_services.py, backend/lcfs/utils/constants.py, backend/lcfs/web/api/compliance_report/views.py, backend/lcfs/web/api/organization/views.py, backend/lcfs/web/api/transaction/repo.py, backend/lcfs/web/api/transaction/services.py, backend/lcfs/web/api/transfer/services.py, backend/lcfs/web/api/transfer/views.py
* Update the MV to expose all 3 types of comments
* Add save call to update_category so the changes are persisted
=> feat: Expose all Transfer Comments

frontend/src/themes/components/grid2.js, frontend/src/themes/index.js, frontend/src/views/Users/AddEditUser/AddEditUser.jsx
* Grid2 only supports row layout now so we cant use column
* Update grid values to always add to 12
=> fix: Remove custom Grid2 styling

backend/lcfs/web/api/compliance_report/summary_service.py
* Supplementals should copy over line 18 into 15 and line 19 into 16 and shouldnt be adding the previous numbers
=> fix: Don't continually add line 15/16

frontend/src/views/Transactions/Transactions.jsx, frontend/src/views/Transactions/components/OrganizationList.jsx
=> Fix: LCFS - Clear filters button on IDIR Transactions #2384

frontend/src/views/FuelExports/__tests__/AddEditFuelExports.test.jsx
Added front-end unit tests for AddEditFuelExports component, covering CI logic, conditional rendering, and edge cases for the "Unknown" provision.
=> Fix: Add unit tests for AddEditFuelExports

backend/lcfs/web/api/calculator/views.py
Fix #2308
- Due to redirect issue, end uses aren't loading
=> Fix: LCFS - BCeID Credit calculator #2308

frontend/src/components/BCFooter/index.jsx, frontend/src/components/BCModal.jsx, frontend/src/components/__tests__/BCFooter.test.jsx, frontend/src/components/__tests__/BCModal.test.jsx, frontend/src/components/__tests__/Footer.test.jsx, frontend/src/components/__tests__/TogglePanel.test.jsx
- feat: BCModal unit tests
- feat: TogglePanel unit tests
- feat: BCFooter unit tests
closes #2412
=> Feat:  Implement Tests for Core UI Components

frontend/src/hooks/useFuelSupply.js, frontend/src/utils/schedules.js, frontend/src/views/AllocationAgreements/_schema.jsx, frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx
* Fixes EER rounding by re-fetching
* Fixes validation error by clearing errors after deletes
* Fixes missing arrows by adding select rendereers
=> fix: Re-load Data and Add Missing Select Renderer

backend/lcfs/tests/services/redis/test_redis.py, frontend/src/assets/locales/en/otherUses.json
- updated other uses text on form
- removed slow irrelevant test
=> Hotfix: Other Uses Form Text

backend/lcfs/tests/final_supply_equipment/conftest.py, backend/lcfs/tests/final_supply_equipment/test_final_supply_equipment_services.py, backend/lcfs/web/api/final_supply_equipment/schema.py, backend/lcfs/web/api/final_supply_equipment/services.py, frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx
* Return flattened fields and add standardized mapping function
=> fix: Fix FSE not saving correctly

backend/lcfs/web/api/calculator/repo.py, backend/lcfs/web/api/compliance_report/summary_repo.py, frontend/src/assets/locales/en/reports.json, frontend/src/components/BCDataGrid/BCGridViewer.jsx, frontend/src/views/ComplianceReports/components/AssessmentCard.jsx, frontend/src/views/ComplianceReports/components/OrganizationAddress.jsx, frontend/src/views/ComplianceReports/components/ReportDetails.jsx, frontend/src/views/ComplianceReports/components/__tests__/OrganizationAddress.test.jsx
Closes: #2515
- Fixes for compliance report summary
- Aligning common UX design for schedules.
=> Feat: LCFS - Edit Address in CR for analyst #2515

backend/lcfs/web/api/compliance_report/services.py
- fix: compliance report list status label, closes #2533
feel free to merge as I will be away until May 20th
=> fix: compliance report list status label

frontend/src/views/CompareReports/CompareReports.jsx, frontend/src/views/CompareReports/__tests__/CompareReports.test.jsx
- fix: fix: compliance report summary compare label, closes #2534
feel free to merge as I will be away until May 20th
=> fix: compliance report summary compare label

frontend/src/views/ComplianceReports/components/HistoryCard.jsx, frontend/src/views/ComplianceReports/components/__tests__/HistoryCard.test.jsx
This PR includes the following fix for hotfix deployment:
- Shows "has met / has not met" statements for government users at all stages.
- Displays indented assessment statements for non-gov users after assessment.
Closes #2560
=> Hot Fix: Assessment Visibility Logic in History Card - 2560

frontend/src/hooks/useAllocationAgreement.js, frontend/src/views/AllocationAgreements/AddEditAllocationAgreements.jsx
- Enabled the download template feature across all environments
- Fixed the 404 error when attempting to download the template
Closes #2273
=> Feat: Enable Download Template on All Envs and Fix 404 - 2273

frontend/src/components/BCDataGrid/components/Editors/DateEditor.jsx, frontend/src/views/FinalSupplyEquipments/_schema.jsx
=> Fix: LCFS - BUG - Fix DateEditor Calendar Icon Clickability in AG Grid #2240

frontend/src/components/BCDataGrid/components/Editors/DateEditor.jsx, frontend/src/views/FinalSupplyEquipments/_schema.jsx
=> Hotfix: Fix FSE date editor and column data fixes

frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/__tests__/buttonConfigs.test.jsx, frontend/src/views/ComplianceReports/buttonConfigs.jsx
=> Feat: LCFS - Return report button #2615

frontend/src/assets/locales/en/reports.json, frontend/src/views/ComplianceReports/components/HistoryCard.jsx, frontend/src/views/ComplianceReports/components/__tests__/AssessmentCard.test.jsx, frontend/src/views/ComplianceReports/components/__tests__/HistoryCard.test.jsx
Encapsulates the Assessment Recommendation section in a styled box.
Closes #2593
=> Feat: Add container box for Assessment Recommendation - 2593

backend/lcfs/web/api/compliance_report/summary_service.py
- changed field types from float to int
=> Fix: no decimals on line 4 - 2613

backend/lcfs/tests/compliance_report/test_update_service.py, backend/lcfs/web/api/compliance_report/update_service.py
- analyst adjustment didn't have a transaction already existing like submitted status report, so we had to check and create a new one once assessed.
=> Fix: analyst adjustment transaction creation - 2630

frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx, frontend/src/views/FinalSupplyEquipments/_schema.jsx
=> Fix: LCFS - BUG - FSE form inputs #2625

backend/lcfs/tests/compliance_report/test_summary_service.py, backend/lcfs/web/api/compliance_report/summary_service.py
- line 17 on summary supplemental creation now calculates available balance
=> Fix: Supplemental Line 17 - 2632

frontend/src/views/ComplianceReports/components/ReportDetails.jsx
fix: hide empty accordions on reports, closes #2640
=> fix: remove empty accordions

backend/lcfs/web/api/fuel_export/actions_service.py, frontend/src/views/FuelExports/_schema.jsx
- fix: fuel export other option energy density null and not saving, closes #2661
=> fix: fuel export energy density

frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/ViewLegacyComplianceReport.jsx, frontend/src/views/ComplianceReports/components/AssessmentCard.jsx
- Fixes duplicate alert banners appearing in multiple schedule accordions
Closes #2638
=> Fix: Prevent Duplicate Banner Alerts on Report Version Creation - 2638

frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/components/AssessmentRecommendation.jsx, frontend/src/views/ComplianceReports/components/AssessmentStatement.jsx, frontend/src/views/ComplianceReports/components/__tests__/AssessmentStatement.test.jsx
- Added a styled container box around the Assessment Recommendation section.
Closes #2593
=> Feat: Wrap Assessment Recommendation in Box - 2593

frontend/src/views/AllocationAgreements/AllocationAgreementChangelog.jsx, frontend/src/views/ComplianceReports/components/ReportDetails.jsx, frontend/src/views/ComplianceReports/components/__tests__/ReportDetails.test.jsx, frontend/src/views/FuelExports/FuelExportChangelog.jsx, frontend/src/views/FuelSupplies/FuelSupplyChangelog.jsx, frontend/src/views/NotionalTransfers/NotionalTransferChangelog.jsx, frontend/src/views/NotionalTransfers/NotionalTransferSummary.jsx, frontend/src/views/OtherUses/OtherUsesChangelog.jsx
Bug fixes: #2622 , #2631 , #2639
=> Fix: Compliance report schedules bug fixes

backend/lcfs/db/dependencies.py
- cleanup of our session dependencies to avoid competing transactions
=> Fix: Set Session Txn Order

backend/lcfs/web/api/compliance_report/constants.py, backend/lcfs/web/api/compliance_report/summary_service.py
- updated line 22 text to show compliance period end date
=> Feat: Line 22 Date Text - 2679

backend/lcfs/tests/compliance_report/test_compliance_report_services.py, backend/lcfs/web/api/compliance_report/services.py, frontend/src/assets/locales/en/reports.json
=> Fix: LCFS - BUG - Analyst creates a Supplemental report history - 2686

backend/lcfs/tests/compliance_report/test_compliance_report_services.py, backend/lcfs/tests/compliance_report/test_summary_service.py, backend/lcfs/tests/compliance_report/test_update_service.py, backend/lcfs/tests/transaction/test_transaction_repo.py, backend/lcfs/web/api/compliance_report/services.py, backend/lcfs/web/api/compliance_report/summary_calculations.md, backend/lcfs/web/api/compliance_report/summary_service.py, backend/lcfs/web/api/compliance_report/update_service.py, backend/lcfs/web/api/transaction/repo.py, frontend/src/views/ComplianceReports/components/HistoryCard.jsx, frontend/src/views/ComplianceReports/components/__tests__/HistoryCard.test.jsx
- updated line 17 available balance calculation
- fixed history card editable text
- added skip summary can_sign for government actions
=> Fix: Line 17 fix, History card Text - 2632 2688

frontend/src/views/ComplianceReports/components/ReportDetails.jsx, frontend/src/views/ComplianceReports/components/__tests__/ReportDetails.test.jsx
- fix: accordion rendering logic, closes #2640
=> fix: accordion rendering logic

backend/lcfs/conftest.py, backend/lcfs/db/connection_management.md, backend/lcfs/db/dependencies.py, backend/lcfs/db/migrations/env.py, backend/lcfs/services/keycloak/authentication.py, backend/lcfs/services/rabbitmq/report_consumer.py, backend/lcfs/tests/test_auth_middleware.py, backend/lcfs/web/api/final_supply_equipment/repo.py, backend/lcfs/web/api/transaction/repo.py, backend/lcfs/web/lifetime.py
- cleaned up redundant database connections
=> Hotfix: Transactions Optimized

backend/lcfs/tests/compliance_report/test_summary_service.py, backend/lcfs/web/api/compliance_report/summary_service.py, frontend/src/views/SupportingDocuments/SupportingDocumentSummary.jsx, frontend/src/views/SupportingDocuments/__tests__/SupportingDocumentSummary.text.jsx
- updated line 17 calc to take into account locked status
- document link text formatting updated
=> Fix: Line 17 Update, Document Link - 2702 2700

frontend/src/views/FuelSupplies/__tests__/_schema.test.jsx, frontend/src/views/FuelSupplies/_schema.jsx
- updated setter with reset logic on fuel supply column changes
=> Fix: updated reset logic for fuel supply - 2741

backend/lcfs/tests/compliance_report/test_compliance_report_services.py, backend/lcfs/tests/compliance_report/test_update_service.py, backend/lcfs/web/api/compliance_report/services.py, backend/lcfs/web/api/compliance_report/update_service.py, backend/lcfs/web/core/decorators.py, frontend/package-lock.json, frontend/src/views/ComplianceReports/__tests__/buttonConfigs.test.jsx, frontend/src/views/ComplianceReports/buttonConfigs.jsx
- updated return logic on analyst adjustments
- fixed delete button visibility logic
=> Fix: Analyst Adjustment Logic - 2784 2781

backend/lcfs/tests/compliance_report/test_compliance_report_services.py, backend/lcfs/web/api/compliance_report/schema.py, backend/lcfs/web/api/compliance_report/services.py, frontend/src/assets/locales/en/reports.json, frontend/src/hooks/useComplianceReports.js, frontend/src/utils/grid/cellRenderers.jsx, frontend/src/views/ComplianceReports/ComplianceReportViewSelector.jsx, frontend/src/views/ComplianceReports/ComplianceReports.jsx, frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/__tests__/ComplianceReportViewSelector.test.jsx, frontend/src/views/ComplianceReports/__tests__/buttonConfigs.test.jsx, frontend/src/views/ComplianceReports/buttonConfigs.jsx, frontend/src/views/ComplianceReports/components/AssessmentCard.jsx, frontend/src/views/ComplianceReports/components/AssessmentRecommendation.jsx, frontend/src/views/ComplianceReports/components/__tests__/ComplianceReportSummary.test.jsx
Fix #2815
- before creating any new compliance report ensure that the latest report is not in Draft status
- Refactor button configs as per the latest button matrix provided by Al.
- in order to not rely solely on cached data in case there are any changes, pass the status from list view to edit view and if there is any mismatch then refetch the report data.
- minor error handling
=> Fix: LCFS - BUG - Missing feature buttons IDIR analyst #2815

frontend/src/assets/locales/en/organization.json
This PR includes the following updates:
- Aligned the text with the official compliance definition provided in ticket #2678
Closes #2678
=> Feat: Update Available Compliance Unit Balance Definition - 2678

frontend/src/views/FuelExports/FuelExportSummary.jsx, frontend/src/views/FuelExports/_schema.jsx, frontend/src/views/FuelSupplies/FuelSupplySummary.jsx, frontend/src/views/FuelSupplies/_schema.jsx
- fix: fuel type other display and energy density units display, closes #2680
=> fix: fuel type other display

frontend/src/views/ComplianceReports/components/ActivityLinksList.jsx
- fix: download compliance report link cursor styling, closes #2773
=> fix: download compliance report link cursor

backend/lcfs/tests/compliance_report/test_penalty_edge_cases.py, backend/lcfs/tests/compliance_report/test_security_and_status_edge_cases.py, backend/lcfs/web/api/compliance_report/summary_service.py
- fixed a bug where penalties calculated were not accounting for previously spent compliance units.
=> Fix: penalty calculation on previously assessed reports

frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx
- fix: early issuance intro text not displaying, closes #2564
=> fix: early issuance intro text

backend/lcfs/db/sql/views/metabase.sql
- #2890 
- drop views before creating
- fix base view of compliance reports.
=> Metabase: Refine the Vw Fuel Supply Analytics Base database view #2826 

frontend/src/views/AllocationAgreements/AllocationAgreementChangelog.jsx, frontend/src/views/ComplianceReports/components/ReportDetails.jsx, frontend/src/views/ComplianceReports/components/__tests__/ReportDetails.test.jsx, frontend/src/views/FuelExports/FuelExportChangelog.jsx, frontend/src/views/FuelSupplies/FuelSupplyChangelog.jsx, frontend/src/views/FuelSupplies/__tests__/FuelSupplyChangelog.test.jsx, frontend/src/views/NotionalTransfers/NotionalTransferChangelog.jsx, frontend/src/views/OtherUses/OtherUsesChangelog.jsx
=> Fix: LCFS - Report caching bug for changelog

backend/lcfs/tests/allocation_agreement/test_alllocation_agreement_importer.py, backend/lcfs/tests/final_supply_equipment/test_final_supply_equipment_importer.py, backend/lcfs/utils/constants.py, backend/lcfs/web/api/allocation_agreement/importer.py, backend/lcfs/web/api/final_supply_equipment/importer.py, frontend/src/components/Documents/DocumentTable.jsx, frontend/src/components/Documents/DocumentUploadDialog.jsx, frontend/src/components/Documents/__test__/DocumentTable.test.jsx, frontend/src/components/Documents/__test__/DocumentUploadDialog.test.jsx, frontend/src/components/ImportDialog.jsx, frontend/src/components/__tests__/ImportDialog.test.jsx, frontend/src/constants/common.js, frontend/src/utils/__tests__/fileValidation.test.js, frontend/src/utils/fileValidation.js
- feat: improve file upload feedback for unsupported file formats, closes #2786 
- feat: improved test suites
=> Upload error message for unsupported file formats

backend/lcfs/tests/compliance_report/test_security_and_status_edge_cases.py, backend/lcfs/web/api/compliance_report/services.py, backend/lcfs/web/api/transaction/repo.py
- transaction released and reinstated on superseded supplemental reports
- tests
=> Fix: Supplemental Txn Logic - 2903 2904

backend/lcfs/db/migrations/versions/2025-06-18-17-00_a1b2c3d4e5f6.py, backend/lcfs/web/api/dashboard/repo.py, backend/lcfs/web/api/dashboard/schema.py, backend/lcfs/web/api/dashboard/services.py, frontend/src/assets/locales/en/dashboard.json, frontend/src/views/Dashboard/components/cards/idir/DirectorReviewCard.jsx, frontend/src/views/Dashboard/components/cards/idir/__tests__/DirectorReviewCard.test.jsx
- New alert for Recommended fuel codes
- Link to filtered Fuel Codes page
- Text update: "awaiting" → "for"
Closes #2590
=> Feat: Add Recommended fuel code alert to Director dashboard - 2590

frontend/src/components/DownloadButton.jsx, frontend/src/layouts/MainLayout/MainLayout.jsx, frontend/src/layouts/MainLayout/components/Crumb.jsx, frontend/src/themes/base/globals.js, frontend/src/themes/components/container.js, frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/Organizations/OrganizationView/OrganizationUsers.jsx, frontend/src/views/Organizations/OrganizationView/OrganizationView.jsx, frontend/src/views/Transactions/Transactions.jsx
- fix: max width tables with padding, closes #2796
=> fix: Lost max width

frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/components/ReportDetails.jsx, frontend/src/views/ComplianceReports/components/__tests__/ReportDetails.test.jsx
This PR includes the fix to auto-expand the attachments accordion after uploading a file.  
Closes #2917
=> Fix: Auto-expand file attachments accordion after upload - 2917

frontend/src/themes/base/globals.js, frontend/src/views/ComplianceReports/components/HistoryCard.jsx
Fix #2938
- fix scrolling issue on grid pagination.
=> Fix: LCFS - BUG - to have has met or to have not to has not met #2938

backend/lcfs/tests/calculator/test_calculator_services.py, backend/lcfs/web/api/calculator/repo.py, backend/lcfs/web/api/calculator/services.py, backend/lcfs/web/api/compliance_report/dtos.py
- credit calculator wasn't returning correct options
- dto optional and duplicate field fix
=> Fix: credit calculator options, supplemental early issuance dto update

frontend/cypress/e2e/Pages/ComplianceReport/ReturnSupplementalReport.test.js, frontend/cypress/e2e/Pages/Transaction/Transaction.test.js, frontend/cypress/e2e/Pages/User/UserCreation.test.js
- Updated out of date cypress logic
=> Fix: Cypress Test Updates

backend/lcfs/tests/allocation_agreement/test_allocation_agreement_services.py, backend/lcfs/tests/compliance_report/test_compliance_report_services.py, backend/lcfs/web/api/compliance_report/repo.py, backend/lcfs/web/api/compliance_report/services.py, backend/lcfs/web/api/compliance_report/views.py, backend/lcfs/web/api/role/schema.py
- fix: draft compliance report schedule changelogs showing for idir users, closes #2993
=> LCFS - BUG - Changelog display

.github/workflows/pr-test.yaml, frontend/src/routes/__tests__/index.test.jsx, frontend/src/routes/__tests__/navigation.test.jsx, frontend/src/routes/__tests__/routeGuards.test.jsx, frontend/src/routes/__tests__/specialRoutes.test.jsx, frontend/src/routes/routeConfig/__tests__/organizationRoutes.test.jsx, frontend/src/routes/routeConfig/__tests__/transactionRoutes.test.jsx, frontend/src/tests/utils/handlers.jsx, frontend/testSetup.js
- feat: vitest tests for routes, 100% coverage, closes #2854
=> LCFS - Add Vitest Test Coverage for Routes

backend/lcfs/db/migrations/versions/2025-07-28-10-12_33ec14737b15.py, backend/lcfs/db/sql/views/metabase.sql, backend/lcfs/web/api/compliance_report/services.py, backend/lcfs/web/api/user/repo.py, frontend/src/views/FinalSupplyEquipments/components/MapComponents.jsx
- Fixes #3030
- fix fuel supply and fuel export metabase views to include compliance_units column.
- fix map controller version issue and implement custom controller.
=> Fix: LCFS - Government adjustment

backend/lcfs/tests/fuel_code/test_fuel_code_exporter.py, backend/lcfs/web/api/fuel_code/export.py
=> Fix LCFS - BUG for downloading fuel code info to Excel #3070

frontend/src/assets/locales/en/reports.json, frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx, frontend/src/views/ComplianceReports/components/AssessmentCard.jsx
=> Feat: LCFS - 30 day supplemental limit

frontend/package-lock.json, frontend/package.json, frontend/vite.config.ts
- feat: pipe client side logs to the terminal
=> Pipe client side logs to the terminal

frontend/src/services/__tests__/useApiService.test.js
- feat: tests for useApiService. 100% coverage in all categories, closes #2855
=> LCFS - Add Vitest Test Coverage for Services

frontend/src/views/ComplianceReports/__tests__/CreditCalculator.test.jsx, frontend/src/views/ComplianceReports/__tests__/buttonConfigs.spec.jsx, frontend/src/views/FinalSupplyEquipments/__tests__/FinalSupplyEquipmentSummary.test.jsx, frontend/src/views/FinalSupplyEquipments/__tests__/GeoMapping.test.jsx, frontend/src/views/FinalSupplyEquipments/__tests__/schema.test.jsx, frontend/src/views/FinalSupplyEquipments/components/__tests__/MapComponents.test.jsx, frontend/src/views/FinalSupplyEquipments/components/__tests__/StatusComponent.test.jsx, frontend/src/views/FinalSupplyEquipments/components/__tests__/TableComponent.test.jsx, frontend/src/views/FinalSupplyEquipments/components/__tests__/utils.test.js, frontend/src/views/Notifications/NotificationMenu/components/__tests__/BCeIDNotificationSettings.test.jsx, frontend/src/views/Notifications/NotificationMenu/components/__tests__/IDIRComplianceManagerNotificationSettings.test.jsx, frontend/src/views/Notifications/NotificationMenu/components/__tests__/NotificationSettings.test.jsx
This PR adds test coverage for view components.
Closes #2977
=> Feat: Add View Component Tests - 2977

backend/lcfs/web/api/transaction/repo.py, frontend/src/hooks/useComplianceReports.js
- fixed a commit where it should have been a flush
=> Fix: Flush on Delete Analyst Adjustment

backend/lcfs/web/api/compliance_report/repo.py, frontend/src/assets/locales/en/organization.json, frontend/src/assets/locales/en/reports.json, frontend/src/views/ComplianceReports/components/AssessmentCard.jsx, frontend/src/views/ComplianceReports/components/OrgDetailsCard.jsx, frontend/src/views/ComplianceReports/components/OrganizationAddress.jsx, frontend/src/views/Organizations/AddEditOrg/AddEditOrgForm.jsx, frontend/src/views/Organizations/AddEditOrg/ReferenceCompareBox.jsx, frontend/src/views/Organizations/AddEditOrg/__tests__/AddEditOrg.test.jsx, frontend/src/views/Organizations/AddEditOrg/__tests__/AddEditOrgForm.test.jsx, frontend/src/views/Organizations/AddEditOrg/__tests__/ReferenceCompareBox.test.jsx, frontend/src/views/Organizations/Organizations.jsx
=> Feat: LCFS - Org update workflow

backend/lcfs/tests/compliance_report/test_summary_service.py, backend/lcfs/web/api/compliance_report/summary_service.py, frontend/src/components/BCForm/__tests__/AddressAutocomplete.test.jsx, frontend/src/views/ComplianceReports/components/SummaryTable.jsx, frontend/src/views/ComplianceReports/components/_schema.jsx
- Updated logic around line 6 calculation to properly cap based on line 4 volume amounts
- Updated tests
=> Fix: line 6 persistence logic updates

frontend/src/assets/locales/en/reports.json, frontend/src/views/ComplianceReports/CreditCalculator.jsx, frontend/src/views/ComplianceReports/__tests__/CreditCalculator.test.jsx
This PR adds the EC formula (quantity * energy density) and updates the credit calculator UI accordingly.
Closes #3096
=> Feat: add EC formula to credit calculator - 3096

frontend/src/views/ComplianceReports/CreditCalculator.jsx
- feat: feat: units for credit calc table, closes #3095
=> LCFS - Add units to figures used in the credit calculator

frontend/src/views/Organizations/OrganizationView/OrganizationDetailsCard.jsx, frontend/src/views/Organizations/OrganizationView/OrganizationView.jsx, frontend/src/views/Organizations/OrganizationView/__tests__/OrganizationView.test.jsx
- feat: organization page tabs, closes #3007
=> LCFS - Organization dashboard

backend/lcfs/db/migrations/versions/2025-08-13-12-42_3f5a7b9c1d2e.py, backend/lcfs/db/sql/views/metabase.sql
This PR includes the creation of a Metabase model for notional transfer data, excluding draft reports.
Closes #2791
=> Feat: Metabase Model for Notional Transfer - 2791

backend/lcfs/tests/final_supply_equipment/test_final_supply_equipment_repo.py, backend/lcfs/web/api/final_supply_equipment/repo.py
- fixed uniqueness check on fse to account for previous report fse versions
=> Fix: Fse duplicate check scoping

frontend/src/components/BCDataGrid/BCDataGridServer.jsx, frontend/src/components/BCDataGrid/BCGridBase.jsx, frontend/src/components/BCDataGrid/__tests__/BCDataGridServer.test.jsx, frontend/src/components/BCDataGrid/__tests__/BCGridBase.test.jsx, frontend/src/components/BCDataGrid/__tests__/BCGridEditor.test.jsx, frontend/src/components/BCDataGrid/__tests__/BCGridViewer.test.jsx, frontend/src/components/BCDataGrid/components/Editors/__tests__/AsyncSuggestionEditor.test.jsx, frontend/src/components/BCDataGrid/components/Editors/__tests__/AsyncValidationEditor.test.jsx, frontend/src/components/BCDataGrid/components/Editors/__tests__/AutocompleteCellEditor.test.jsx, frontend/src/components/BCDataGrid/components/Editors/__tests__/DateEditor.test.jsx, frontend/src/components/BCDataGrid/components/Editors/__tests__/LargeTextareaEditor.test.jsx, frontend/src/components/BCDataGrid/components/Editors/__tests__/NumberEditor.test.jsx, frontend/src/components/BCDataGrid/components/Editors/__tests__/TextCellEditor.test.jsx, frontend/src/components/BCDataGrid/components/Filters/__tests__/BCColumnSetFilter.test.jsx, frontend/src/components/BCDataGrid/components/Filters/__tests__/BCDateFloatingFilter.test.jsx, frontend/src/components/BCDataGrid/components/Filters/__tests__/BCSelectFloatingFilter.test.jsx, frontend/src/components/BCDataGrid/components/Renderers/__tests__/AccessibleHeader.test.jsx, frontend/src/components/BCDataGrid/components/Renderers/__tests__/ActionsRenderer.test.jsx, frontend/src/components/BCDataGrid/components/Renderers/__tests__/RequiredHeader.test.jsx, frontend/src/components/BCDataGrid/components/Renderers/__tests__/ValidationRenderer.test.jsx, frontend/src/components/BCDataGrid/components/Renderers/__tests__/ValidationRenderer2.test.jsx, frontend/src/components/BCDataGrid/components/StatusBar/__tests__/BCPagination.test.jsx, frontend/src/components/BCDataGrid/components/StatusBar/__tests__/BCPaginationActions.test.jsx
- feat: tests for core bcgrid components, filters, editors, renderers, status bar, closes #2974
=> LCFS - Add Test Coverage for BCDataGrid System (0% → 80%)

frontend/src/views/ComplianceReports/CreditCalculator.jsx
=> Feat: LCFS - Credit calculator, remove radio button #3167

frontend/src/views/Organizations/OrganizationView/OrganizationProfile.jsx, frontend/src/views/Organizations/OrganizationView/__tests__/OrganizationProfile.test.jsx
This PR includes adding organization type display on the detail view.
Closes #3028
=> Feat: Show Organization Type on Detail View - 3028

backend/lcfs/db/migrations/versions/2025-08-21-15-47_32a1f93375bd.py, backend/lcfs/db/models/fuel/FuelType.py, backend/lcfs/tests/compliance_report/test_summary_repo.py, backend/lcfs/tests/compliance_report/test_summary_service.py, backend/lcfs/tests/other_uses/test_other_uses_repo.py, backend/lcfs/web/api/compliance_report/summary_repo.py, backend/lcfs/web/api/compliance_report/summary_service.py, backend/lcfs/web/api/other_uses/repo.py
- Updated other use options list
- Line 1 volume aggregation updated
=> Hotfix: v1.1.2.2

backend/lcfs/web/api/notification/repo.py
=> Fix: LCFS - Internal Server Error When Director Attempts to Record Transfer #3219

frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx
- Moved location of report details component
=> Fix: Documents Early Issuance - 3225

backend/lcfs/db/migrations/versions/2025-09-03-02-13_c19276038926.py, backend/lcfs/db/models/compliance/ChargingEquipment.py, backend/lcfs/db/models/compliance/ChargingSite.py, backend/lcfs/utils/unique_key_generators.py
=> Feat: LCFS - FSE to charging site data migrations

backend/lcfs/web/api/charging_site/repo.py, backend/lcfs/web/api/charging_site/services.py, backend/lcfs/web/api/charging_site/views.py, frontend/src/assets/locales/en/reports.json, frontend/src/constants/routes/apiRoutes.js, frontend/src/hooks/useChargingSite.js, frontend/src/routes/routeConfig/reportRoutes.jsx, frontend/src/routes/routes.js, frontend/src/views/ChargingSite/ChargingSitesList.jsx, frontend/src/views/ChargingSite/__tests__/ChargingSitesList.test.jsx, frontend/src/views/ChargingSite/_schema.jsx, frontend/src/views/ComplianceReports/ReportsMenu.jsx
- feat: frontend work for idir charging site index page, closes #2588
- feat: addition of endpoint to fetch all charging sites, with appropriate hook on the frontend
=> LCFS - IDIR Charging site index page

backend/lcfs/services/keycloak/authentication.py
- Updated the authentication workflow to resolve signing keys directly from the cached JWKS payload, handle missing or rotated keys, and continue JWT validation without additional network calls to avoid connection failures.
=> Fix: Auth connection issue fix.
