bcgov/lcfs

- backend/lcfs/db/seeders/common/organization_seeder.py
- frontend/src/layouts/navbar/Navbar.jsx
- frontend/src/views/organization/AddOrganization.jsx
This PR adds the organization's name to the top banner of the app.
It also includes a minor refactor for responsive spacing in the "Add Organization" form.
Closes #154
> Feat: Add organization name display in top banner - 154

- frontend/src/components/ProgressBreadcrumb.jsx
- frontend/src/components/ProgressBreadcrumb.test.jsx
This pull request introduces the ProgressBreadcrumb component, designed to effectively track and display progress stages on the new transfer page.
Closes #213
> Feat: Add progress tracking breadcrumb component - 213

- frontend/src/constants/roles.js
- frontend/src/hooks/useCurrentUser.js
- frontend/src/views/AddTransaction.jsx
- frontend/src/views/Transactions.jsx
This pull request adds a 'New Transfer' button to the Transactions page, available exclusively for users with the 'Transfers' role.
The updated `useCurrentUser` hook now aligns better with user authentication, simplifies handling success and errors, and adds a clear, documented function for checking user roles.
Closes #212
> Feat: Add new transfer button and landing page - 212

- frontend/src/App.jsx
- frontend/src/views/Organizations/ViewOrganization/_schema.js
- fix: org creation error fixed in #222 
- refactor: org creation improvements in #222 
- fix: grid column width
- feat: breadcrumb added
notes:
- in reserve and compliance units are generated at random every render. This can be replaced with actual values once these values are saved to the organizations.
> Fix: org view 160

- frontend/src/views/Transactions/Transactions.jsx
This PR updates the label of the "New Transaction" button to "New Transfer" for BCeID users on the Transactions page, enhancing user understanding and consistency within the application. 
Closes #212
> Fix: Update "New Transaction" Button Label - 212

- frontend/src/views/Transfers/AddEditTransfer/AddEditTransfer.jsx
This PR corrects the introductory sentence on the new transfer page by removing an extraneous `&nbsp;` and ensuring "director" is in lowercase.
Closes #214
> Fix: Cleanup Intro Sentence on New Transfer Page - 214

- frontend/public/config.js
- frontend/src/constants/config.js
Reverts bcgov/lcfs#416
Revert the changes, move the config.js to config/config.js, Openshift is able to override config/config.js but requires no other files in that folder
> Revert "fix: dev config file"

- backend/lcfs/web/api/organizations/schema.py
- frontend/src/views/Organizations/AddEditOrg/AddEditOrg.jsx
This PR addresses a few issues in the edit organization form.
1. Fixed the issue where the "Operating Name of Organization" value was not loading correctly in the edit organization form.
2. Addressed the problem with loading "Address in B.C." values in the edit organization form.
3. Implemented auto-check for "Same as Legal Name" and "Same as Address for Service" checkboxes during the initial load in the edit organization form.
4. Eliminated redundant validation errors for "Address in B.C." fields when "Same as Address for Service" is selected.
Also, I can confirm that the postal code validation works for both Canadian postal codes (with or without space) and US postal codes.
Closes #165
> Fix: Resolve Edit Organization Form Issues - 165

- backend/lcfs/web/api/organizations/repo.py
This PR implements alphabetical sorting for the 'Select an Organization' drop-down within the transfer feature.
Closes #502
> Feat: Sort Organizations Alphabetically in Dropdown - 502

- backend/lcfs/db/migrations/versions/2024-04-03-14-18_abcdef123456.py
- backend/lcfs/db/models/TransactionView.py
- backend/lcfs/db/models/TransferStatus.py
- backend/lcfs/db/seeders/common/transfer_status_seeder.py
- backend/lcfs/db/seeders/test_seeder.py
- backend/lcfs/tests/transaction/test_transaction_repo.py
- backend/lcfs/tests/transaction/transaction_payloads.py
- backend/lcfs/web/api/transaction/repo.py
This PR addresses the requirement to clean up the visibility of transfers based on their status, ensuring that transfers are only visible to the appropriate parties (transferor, transferee, government) at the correct times.
Closes #491
> Feat: Clean up transfer visibility by status - 491

- frontend/src/components/BCDataGrid/BCDataGridServer.jsx
- frontend/src/views/Transactions/Transactions.jsx
- frontend/src/views/Transfers/AddEditViewTransfer.jsx
This PR introduces the feature to highlight transaction rows in the Transactions page after a state/status change.
Currently, the updated transaction row is highlighted only when returning to the transactions page. If the row is on a page other than the first, users must navigate to it themselves. I also developed a feature for automatically navigating to the page containing the transaction, but it consumed a lot of resources. This required running all queries within `web/api/transaction/repo.py::get_transactions_paginated` to find the transaction's exact position. Please advise if this feature should still be added.
Closes #497
> Feat: Highlight Transaction Row on Status Change - 497

- frontend/src/components/BCBadge/BCBadgeRoot.jsx
This PR updates the capitalization of pill labels to align with styling preferences across the application. Instead of all caps, only the first letter of the first word will be capitalized.
Closes #504
> Fix: Update Pill Capitalization for Consistency - 504

- frontend/src/utils/cellRenderers.jsx
- frontend/src/views/Users/AddEditUser/AddEditUser.jsx
- frontend/src/views/Users/AddEditUser/_schema.js
This PR changes the capitalization of 'active' and 'inactive' status labels to start with an uppercase letter, aligning them with other labels for consistency. This issue was identified during testing.
Closes #504
> Fix: Capitalize Status Labels - 504

- frontend/src/views/Organizations/AddEditOrg/_schema.js
This PR addresses the postal code validation error that occurs when saving the LCFS2 organization profile. The fix ensures that both Canadian postal codes and US ZIP codes  are supported in the following formats:
Canadian Postal Codes:
- A1A 1A1: Letter, digit, letter, **[space]**, digit, letter, digit.
- A1A1A1: Letter, digit, letter, digit, letter, digit.
US ZIP Codes:
- 12345: Five digits.
- 12345-6789: Five digits followed by a hyphen and four digits.
With these changes, users can now edit and successfully save changes without encountering the postal code error.
Closes #467
> Fix: Correct Postal Code Validation on LCFS2 Save - 467

- backend/lcfs/services/keycloak/authentication.py
- backend/lcfs/services/keycloak/dependencies.py
This PR ensures that usernames and emails are case insensitive when logging in.
Closes #578
> Fix: Make Username & Email Case Insensitive - 578

- backend/lcfs/web/api/initiative_agreement/schema.py
- backend/lcfs/web/api/initiative_agreement/services.py
- backend/lcfs/web/api/internal_comment/schema.py
- frontend/src/components/InternalComments/InternalCommentForm.jsx
- frontend/src/components/InternalComments/InternalCommentList.jsx
- frontend/src/components/InternalComments/index.jsx
- frontend/src/views/Transactions/AddEditViewTransaction.jsx
- frontend/src/views/Transactions/_schema.yup.js
- frontend/src/views/Transactions/buttonConfigs.jsx
This PR implements the transaction internal comments feature on the new transaction page with conditional button visibility based on the step in the transaction creation process.
Closes #347
> Feat: Implement transaction internal comments on new transaction page - 347

- frontend/src/views/Transactions/components/Comments.jsx
This PR ensures that the comments box is collapsed by default on the new transaction page.
Closes #346
> Fix: Ensure comments box is collapsed by default on new transaction page - 346

- frontend/src/views/Transactions/Transactions.jsx
This PR disables the export to XLS functionality in AG Grid on the transactions page.
> Fix: Disable AG Grid Export to XLS on Transactions Page

- frontend/src/layouts/MainLayout/components/SupplierBalance.jsx
- frontend/src/views/Dashboard/components/cards/bceid/OrgBalanceCard.jsx
This PR resolves the issue where reserve compliance units were displayed as negative values, ensuring they are now shown as positive values.
Closes #645
> Fix: Ensure reserve units display as positive values - 645

- frontend/src/assets/locales/en/transaction.json
- frontend/src/views/Transactions/components/OrgTransactionDetails.jsx
- frontend/src/views/Transactions/components/__tests__/OrgTransactionDetails.test.jsx
This PR applies the requested changes to the transaction, including hiding the comments label when no comments are provided and duplicating the approved date if no effective date is entered.
Closes #646
> Fix: Apply requested changes to transaction - 646

- frontend/src/views/Organizations/ViewOrganization/ViewOrganization.jsx
- frontend/src/views/Organizations/ViewOrganization/_schema.js
- frontend/src/views/Transactions/components/OrganizationList.jsx
- frontend/src/views/Transactions/components/TransactionDetails.jsx
- frontend/src/views/Transfers/components/OrganizationBadge.jsx
This PR ensures that in reserve units do not display as negative values across various IDIR pages.
Closes #645
> Fix: Ensure in reserve units do not display as negative values - 645

- backend/lcfs/web/api/transaction/services.py
- frontend/src/views/Transactions/AddEditViewTransaction.jsx
- frontend/src/views/Transactions/__tests__/AddEditViewTransaction.test.jsx
- frontend/src/views/Transactions/_schema.js
- frontend/src/views/Transactions/components/OrgTransactionDetails.jsx
- frontend/src/views/Transactions/components/__tests__/OrgTransactionDetails.test.jsx
- frontend/src/views/Transfers/AddEditViewTransfer.jsx
This PR adds prefixes to transaction IDs and compliance report IDs for better distinction and clarity.
Closes #677
> Feat: Add prefixes to transaction IDs and compliance reports - 677

- backend/lcfs/db/seeders/dev/expected_use_types_seeder.py
- backend/lcfs/web/api/compliance_report/views.py
- backend/lcfs/web/api/other_uses/repo.py
- backend/lcfs/web/api/other_uses/schema.py
- backend/lcfs/web/api/other_uses/services.py
- frontend/src/assets/locales/en/otherUses.json
- frontend/src/components/BCDataGrid/BCDataGridEditor.jsx
- frontend/src/views/OtherUses/_schema.jsx
- Ag-grid option to save on lost cell focus added
- Expected use other field logic added for 'Other' option
- Update seeds for expected use to show only the 2 required options
- Switched units table options to load correct list
> Fix: Expected use logic - 723

- backend/lcfs/web/api/fuel_code/schema.py
This PR fixes the issue where existing fuel codes were not displayed and the input form was missing when adding a new code.
Closes #861
> Fix: Resolve Fuel Code Form Display Issues - 861

- backend/lcfs/web/api/allocation_agreement/repo.py
- backend/lcfs/web/api/final_supply_equipment/repo.py
- backend/lcfs/web/api/fuel_export/repo.py
- backend/lcfs/web/api/fuel_supply/repo.py
- backend/lcfs/web/api/notional_transfer/repo.py
- backend/lcfs/web/api/other_uses/repo.py
- fix: compliance report schedules row sorting to sot by ID, closes #912 
Sort comparator function for ag grid does not seem to affect the sorting of the rows. resorted to sorting the returned backend data as the order for that was what was affecting the sort order.
> fix: compliance report schedules row ordering

- backend/lcfs/tests/compliance_report/test_compliance_report_views.py
- backend/lcfs/tests/compliance_report/test_update_service.py
- backend/lcfs/tests/other_uses/test_other_uses.py
- backend/lcfs/web/api/compliance_report/repo.py
- backend/lcfs/web/api/compliance_report/summary_service.py
- backend/lcfs/web/api/compliance_report/update_service.py
- backend/lcfs/web/api/compliance_report/views.py
- frontend/src/constants/routes/apiRoutes.js
- frontend/src/hooks/useComplianceReports.js
- frontend/src/layouts/MainLayout/components/Navbar.jsx
- frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx
Previously any changes to fuel supply or other fields would cause line 6 to be overwritten. The endpoint was also being called twice.
This change aims to start fixing the issue, by updating the get endpoint to IDEALLY only re-calculate if something has changed however this is not currently working.
Changes:
* Unify get and put to have the same structure, Report -> Summary is 1:1 so there is no need to pass in ID
* Remove  need to pass in summary_id for get as there can only ever be one per report
* Begin to clean up line calculation code to use less / clear checks
* Update useComplianceReport to not invalidate its own data and instead set it
* Fix typos
closes: #895 #896
> feat: Enable saving of Line 6 without overwriting

- frontend/src/views/AllocationAgreements/AddAllocationAgreements.jsx
- frontend/src/views/AllocationAgreements/_schema.jsx
Fix bug in allocation agreements in the following scenarios:
- When changing the value of `Determining Carbon Intensity` field, `Fuel code` field value should be reset:
- Formatting `CI of fuel` field to show 2 decimal places in the UI. We keep storing the original value to avoid losing precision.
> LCFS-968: Bug fix in Allocation agreements for Fuel code and CI of fuel

- frontend/src/assets/locales/en/reports.json
- frontend/src/components/BCDataGrid/BCGridEditor.jsx
- frontend/src/views/AllocationAgreements/AddAllocationAgreements.jsx
- frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx
- frontend/src/views/ComplianceReports/components/_schema.jsx
- frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx
- frontend/src/views/FuelExports/AddEditFuelExports.jsx
- frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx
- frontend/src/views/NotionalTransfers/AddEditNotionalTransfers.jsx
- frontend/src/views/OtherUses/AddEditOtherUses.jsx
This PR relocates the validation alert directly under the table to prevent UI shifting and fixes the missing compliance report type text in the index page.
Closes #973, #975
> Refactor: Relocate Validation Alert and Fix Missing Report Type - 973, 975

- frontend/src/components/RequireAuth.jsx
- frontend/src/layouts/MainLayout/components/Navbar.jsx
* Token refresh causes loading to go true, this clears all components from the page and resets their status
* By not loading, components on the page keep their state
> fix: Don't unload components when RequireAuth is loading

- frontend/src/components/BCDataGrid/BCGridEditor.jsx
- frontend/src/views/ComplianceReports/components/ReportHistoryCard.jsx
- frontend/src/views/FuelCodes/AddFuelCode/AddFuelCode.jsx
This PR addresses two issues: it adds the necessary alert on the Fuel Code input page for the IDIR side, and ensures the report history box is visible for submitted compliance reports.
Closes #973 and #1002
> Fix: Add alert on Fuel Code input page and show report history for compliance reports - 973, 1002

- backend/lcfs/db/dependencies.py
- backend/lcfs/utils/performance_profiler.py
- backend/lcfs/utils/query_analyzer.py
* Log all queries with a warning slower than 1.3 seconds so we can start looking into performance
* Auto enable query profile for dev environments
* Add a performance profile so developers can quickly profile code to find bottlenecks
> feat: Add slow query tracker and function profiler

- backend/lcfs/web/api/allocation_agreement/services.py
**Issue**
- Fix issue when saving changes in Allocation agreements throwing this error in backend:
AttributeError: 'NoneType' object has no attribute 'fuel_code'
- The issue is that null values are possible in `fuel_code` field for `existing_allocation_agreement` (data from `allocation_agreement` table queried in database) or `allocation_agreement_data` (data from payload sent with the POST request).
**Valid scenarios when saving fuel_code**
- When selecting the different values from Determining Carbon Intensity, fuel_code is behaving as follows:
- Default carbon intensity -section 19 (b): fuel_code is empty and not editable.
- Fuel code - section 19 (b) (i): User can select any `active` fuel_code
- Prescribed carbon intensity - section 19 (a): fuel_code is empty and not editable. …
> LCFS-1033: Allocation agreement schedule edits not persisting when save is selected

- backend/lcfs/web/api/allocation_agreement/schema.py
- backend/lcfs/web/api/fuel_code/repo.py
- frontend/src/views/AllocationAgreements/AddAllocationAgreements.jsx
- frontend/src/views/AllocationAgreements/_schema.jsx
**Issue**
The `provisionOfTheAct field` (labeled as "_Determining Carbon Intensity_") was displaying all available options, regardless of the selected fuel type. This caused confusion since not all provisions are applicable to every fuel type.
**Fix**
The `provisionOfTheAct` field is now dynamically filtered based on the selected `Fuel Type` field, following the existing relationship in the database. The field will only display the provisions that are relevant to the chosen fuel type.
The provisions displayed are based on the following mappings:
```
fuel_type_id|fuel_type              |provision_1_name                            |provision_2_name                              |
------------+-----------------------+--------------------------------------------+-------------------------------- …
```
> LCFS-1055: Allocation agreement schedule is allowing all fuel types to chose any of the 3 determining carbon intensity options

- backend/lcfs/db/migrations/versions/2024-10-18-19-48_bb5504e743a0.py
**Issue**
Last migration 2024-10-18-19-48_bb5504e743a0.py should have included revises `a731a32947dc`:
2024-10-18-19-48_bb5504e743a0.py:
"""Update 'price_per_unit' column from Integer to Numeric(10, 2).
Revision ID: bb5504e743a0
Revises: 4f25f8811872 --> This should be the previous migrationa731a32947dc
Create Date: 2024-10-18 19:48:34.877657
"""
The previous migration is `2024-10-18-19-46_a731a32947dc.py`:
"""Use Numeric for 2 Decimal Columns
Revision ID: a731a32947dc
Revises: 4f25f8811872
Create Date: 2024-10-18 19:46:48.189455
"""
The above is creating two heads in alembic:
alembic heads
a731a32947dc (head)
bb5504e743a0 (head)
**Fix:**
Merge the two migrations to have one head.
> hotfix: Fixing two heads in alembic.

- frontend/src/constants/routes/apiRoutes.js
This PR fixes the issue where the dashboard widget counter for directors was always showing 0 due to an incorrect URL. 
Closes #992
> Fix: Removed trailing slash in director review counts URL - 992

- backend/lcfs/web/core/decorators.py
#1014
> @prv-proton @Grulin yes I think it would be better to just be blank, so give no error at all. An error message like this may provide information that we don't want to be giving out.
Fix for above, currently the error message is changed to Not found for all 403 error messages.
Need to confirm with Al, before the changes are approved.
> Fix: Error messages for permission access

- backend/lcfs/web/api/compliance_report/repo.py
- backend/lcfs/web/api/compliance_report/update_service.py
#1005
> Everything works great but the Issue assessment button gives a 500 error
Since the reports were already created in dev environment, without creating a transaction record in RESERVED status, existing reports were failing. Hence have made changes to create a new transaction as ADJUSTMENT for the final report assessment in case there is no existing transaction.
> Fix: Bug fix for compliance report director assessment

- frontend/src/hooks/useComplianceReports.js
Quick fix for the issue in dev.
getComplianceReport call is disabled if orgID is not provided, added fix to bypass this for IDIR users and async call introduced.
> Fix: Compliance report loading issue in dev

- backend/lcfs/web/core/decorators.py
* If the payload is a file, this breaks. As it tries to consume the file buffer that was already consumed.
> fix: Remove non-JSON payload logic from decorators

- frontend/src/views/FinalSupplyEquipments/FinalSupplyEquipmentSummary.jsx
**Additional work:**
Adding FSE fields to Report Details view
[PR related](https://github.com/bcgov/lcfs/pull/1162)
> LCFS-1112: Adding FSE fields to Report details

- backend/lcfs/tests/compliance_report/test_compliance_report_services.py
- backend/lcfs/tests/compliance_report/test_compliance_report_views.py
- backend/lcfs/web/api/compliance_report/services.py
- backend/lcfs/web/api/compliance_report/views.py
- frontend/src/views/ComplianceReports/components/AssessmentCard.jsx
* Re-use existing status mask from list reports on get compliance report
* This correctly masks the status for organizations
> fix: Filter Report Status on Get Report Endpoint

- backend/lcfs/tests/compliance_report/conftest.py
- backend/lcfs/tests/compliance_report/test_compliance_report_repo.py
- backend/lcfs/tests/compliance_report/test_compliance_report_views.py
- backend/lcfs/tests/compliance_report/test_summary_service.py
- backend/lcfs/tests/compliance_report/test_update_service.py
- backend/lcfs/web/api/compliance_report/repo.py
- backend/lcfs/web/api/compliance_report/schema.py
- backend/lcfs/web/api/compliance_report/summary_service.py
- backend/lcfs/web/api/compliance_report/update_service.py
- backend/lcfs/web/api/compliance_report/views.py
- frontend/src/assets/locales/en/reports.json
- frontend/src/views/ComplianceReports/components/ComplianceReportSummary.jsx
- frontend/src/views/ComplianceReports/components/SigningAuthorityDeclaration.jsx
* Add new UI for SigningAuthorityDeclaration to have a disabled state with a warning message
* Calculate can_sign based on number of records in each schedule and use to set flag
* Update submit logic to check the same flag and raise an error
* Update compliance summary calculation to only call get effective records one
* Update / Add tests accordingly
> feat: Add can_sign to compliance summary

- backend/lcfs/db/migrations/versions/2024-11-12-13-14_2d98674000f3.py
- backend/lcfs/db/models/notification/NotificationChannelSubscription.py
- backend/lcfs/db/models/notification/NotificationMessage.py
- backend/lcfs/db/models/notification/NotificationType.py
- backend/lcfs/db/models/organization/Organization.py
- backend/lcfs/tests/notification/test_notification_repo.py
- backend/lcfs/tests/notification/test_notification_services.py
- backend/lcfs/tests/notification/test_notification_views.py
- backend/lcfs/web/api/notification/repo.py
- backend/lcfs/web/api/notification/schema.py
- backend/lcfs/web/api/notification/services.py
- backend/lcfs/web/api/notification/views.py
- backend/lcfs/web/core/decorators.py
Include the following endpoints:
Description: Get all Notifications by User ID
GET /api/notifications/
Description: Get a Notification by ID
GET /api/notifications/{notification_id}
Description: Get Unread Notifications
GET /api/notifications/count
Description: Save a Notification
POST /api/notifications/save
Description: Get Notification Channel Subscriptions by User ID
GET /api/notifications/subscriptions
Description: Get Notifications Channel Subscriptions By ID
GET /api/notifications/subscriptions/{notification_channel_subscription_id}
Description: Save a Notification Channel Subscription
POST /api/notifications/subscriptions/save
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=85582754&issue=bcgov%7Clcfs%7C1149)
> LCFS-1149: Notification System for LCFS

- frontend/src/assets/locales/en/transfer.json
- frontend/src/views/Transfers/components/TransferDetails.jsx
- frontend/src/views/Transfers/components/__tests__/TransferDetails.test.jsx
This PR adds a line of instructional text to guide users on zero-dollar credit transfers by specifying that an explanation should be added in the comment box.
Closes #1276
> Feat: Add instructional text for zero-dollar transfers - #1276

- frontend/src/views/Users/AddEditUser/AddEditUser.jsx
- frontend/src/views/Users/AddEditUser/__tests__/test.mock.js
- frontend/src/views/Users/AddEditUser/components/BCeIDSpecificRoleFields.jsx
This PR hides the "Read only" role from the Edit User page to prevent accidental assignment of an incomplete role, improving security.
Closes #1294
> Fix: Remove 'Read only' role option - #1294

- frontend/src/views/ComplianceReports/components/SummaryTable.jsx
* backend only takes int, string was failing pydantic validation
* Remove empty tag that wasn't needd
> fix: Default Summary Table inputs to 0 instead of empty string

- backend/lcfs/web/api/final_supply_equipment/schema.py
- frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx
- frontend/src/views/FinalSupplyEquipments/_schema.jsx
This PR updates the duplicate row function to exclude copying the 'kWh usage' field, ensuring users manually input its value for better data accuracy.
Closes #1279
> Feat: Prevent copying 'kWh usage' field in duplicate row function - #1279

- backend/lcfs/web/api/monitoring/views.py
- backend/lcfs/web/application.py
* Add code to bypass auth check for health endpoint
> feat: Bypass auth for health check

- backend/lcfs/db/migrations/versions/2024-12-09-22-33_cd8698fe40e6.py
- backend/lcfs/db/models/user/UserProfile.py
- backend/lcfs/tests/user/test_user_repo.py
- backend/lcfs/tests/user/test_user_views.py
- backend/lcfs/tests/user/user_payloads.py
- backend/lcfs/web/api/user/repo.py
- backend/lcfs/web/api/user/schema.py
- backend/lcfs/web/api/user/services.py
- backend/lcfs/web/api/user/views.py
- frontend/src/constants/routes/apiRoutes.js
- frontend/src/views/Notifications/NotificationMenu/components/BCeIDNotificationSettings.jsx
- frontend/src/views/Notifications/NotificationMenu/components/NotificationSettingsForm.jsx
This PR removes the notification email field and updates the logic to use the profile email for notifications.
> Fix: Remove Notification Email and Use Profile Email

- frontend/src/views/FinalSupplyEquipments/_schema.jsx
User can not access FinaL Supply Equipment due to error in Typography not found. This component was replaced for BCTypography.
> hotfix: Replace Typography with BCTypography

- frontend/src/views/AllocationAgreements/AllocationAgreementSummary.jsx
- frontend/src/views/FinalSupplyEquipments/FinalSupplyEquipmentSummary.jsx
- frontend/src/views/FuelExports/FuelExportSummary.jsx
- frontend/src/views/FuelSupplies/FuelSupplySummary.jsx
- frontend/src/views/NotionalTransfers/NotionalTransferSummary.jsx
- frontend/src/views/OtherUses/OtherUsesSummary.jsx
- feat: clicking on one of the summary rows in compliance reports page will navigate to its respective pages, closes #1391
> feat: clickable summaries

- backend/lcfs/db/migrations/versions/2024-12-12-21-43_5d729face5ab.py
- backend/lcfs/db/seeders/common/seed_fuel_data.json
This PR updates the default_carbon_intensity for 'Other diesel' fuel type to 100.21.
Closes #1425
> Fix: Correct default carbon intensity for 'Other Diesel fuel' type - #1425

- backend/lcfs/web/api/fuel_export/repo.py
- backend/lcfs/web/application.py
- frontend/src/assets/locales/en/allocationAgreement.json
- frontend/src/assets/locales/en/fuelExport.json
- frontend/src/assets/locales/en/fuelSupply.json
- frontend/src/assets/locales/en/otherUses.json
- frontend/src/views/AllocationAgreements/AddEditAllocationAgreements.jsx
- frontend/src/views/AllocationAgreements/_schema.jsx
- frontend/src/views/FuelExports/AddEditFuelExports.jsx
- frontend/src/views/FuelExports/_schema.jsx
- frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx
- frontend/src/views/FuelSupplies/_schema.jsx
- frontend/src/views/OtherUses/AddEditOtherUses.jsx
- frontend/src/views/OtherUses/_schema.jsx
This PR implements logic to enforce mandatory fuel code selection in schedules when "Fuel code - section 19 (b) (i)" is chosen.
Closes #1429
> Feat: Enforce mandatory fuel code validation for schedules - 1429

- frontend/src/components/BCDataGrid/components/Editors/DateEditor.jsx
- frontend/src/views/AllocationAgreements/AddEditAllocationAgreements.jsx
- frontend/src/views/AllocationAgreements/_schema.jsx
- frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx
- frontend/src/views/FuelExports/AddEditFuelExports.jsx
- frontend/src/views/FuelExports/_schema.jsx
- frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx
- frontend/src/views/NotionalTransfers/AddEditNotionalTransfers.jsx
- frontend/src/views/OtherUses/AddEditOtherUses.jsx
- feat: reports default to having a blank row on load
- feat: first cell of these blank rows will auto open/select on load
- 
closes #1397
> feat: reports to have blank row on load + open first cell

- frontend/package-lock.json
- frontend/package.json
- frontend/src/main.jsx
- frontend/src/services/useApiService.js
- feat: 400+ errors display an error toast globally using notistack(mui underneath) for imperative handling. closes #1441 
note: mui v6 has their own implementation via their toolpad package. would be good to look into later when/if upgrading mui to v6.
> feat: toast on 400+ errors

- frontend/src/views/FuelCodes/AddFuelCode/AddEditFuelCode.jsx
- The _schema for AddEditFuelCode is expecting an array of strings.
- Added transformation for transport modes
Open an existing fuel code/ create a fuel code and confirm the transport modes are included after creation:
> LCFS-1446: Fuel code Feedstock transport mode & Finished fuel transport mode not displaying values

- frontend/src/views/AllocationAgreements/AddEditAllocationAgreements.jsx
- frontend/src/views/AllocationAgreements/_schema.jsx
- frontend/src/views/NotionalTransfers/AddEditNotionalTransfers.jsx
- frontend/src/views/NotionalTransfers/_schema.jsx
BCeID user cannot add her/his own organization as Transactional Partner in Allocation Agreements and Notional Transfers:
Legal name of transaction partner not showing own organization:
When BCeID user type own organization, then an error is displayed:
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=90870933&issue=bcgov%7Clcfs%7C1453)
> LCFS-1453: Legal name of transaction partner

- backend/lcfs/web/api/final_supply_equipment/repo.py
- frontend/src/views/FinalSupplyEquipments/FinalSupplyEquipmentSummary.jsx
* Sort both paginated and non paginated by create date asc to match other schedules
* Fix kWH usage column to use nice number formatter without decimals
> fix: Sorting & Display of FSE

- frontend/src/views/OtherUses/OtherUsesSummary.jsx
- fix: filters showing in header of other uses summary in compliance reports page, closes #1458
> fix: filter showing on other uses summary

- frontend/src/services/useApiService.js
- fix: fixes a bug where cell changes dont return the correct alert
> fix: grid alert not returning correct alert

- backend/lcfs/web/api/fuel_supply/repo.py
When there are more than 40 Fuel-supplies records, the time taken to load the records grows. 
Endpoint /api/fuel-supply/list-all calls the function `get_effective_fuel_supplies` which is executing a query to obtain the fuel supplies lasting 23 secs aprox.
The current changes are reducing significativily the time to  3 secs aprox
Used the following 54 FS records:
```
INSERT INTO public.fuel_supply (compliance_report_id,quantity,units,compliance_units,target_ci,ci_of_fuel,energy_density,eer,energy,fuel_type_other,fuel_category_id,fuel_code_id,fuel_type_id,provision_of_the_act_id,end_use_id,create_date,update_date,create_user,update_user,group_uuid,"version",user_type,action_type,uci) VALUES
(1,20,'Litres',0,NULL,88.83,36.00,1.00,720,NULL,3,NULL,11,3,NULL,'2024-12-19 …
```
> LCFS-1457: Large number of records in Fuel Supply breaks report

- backend/lcfs/services/s3/client.py
- backend/lcfs/web/api/document/views.py
- frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx
- frontend/src/views/ComplianceReports/components/ReportDetails.jsx
Extend the logic of Supporting Documents to allow Analyst to attach Supporting Documents as long as the compliance report status is submitted or assessed. Supporting documents section is visible at all times.
**New Logic:**
- BCeID user can attach supporting documents to a compliance report under `draft`:
- Analyst user can check the `submitted` report and attach supporting documents:
- Under `submitted` report, BCeID user can see the supporting documents section, but not modify docs in the section:
> LCFS-1426: Upload file attachements compliance reports for Analyst user

- etl/nifi_scripts/user.groovy
> Fix: LCFS - Fix ETL Role Mapping Between TFRS and LCFS #1594

- frontend/src/assets/locales/en/fuelCode.json
- frontend/src/components/BCDataGrid/BCDataGridServer.jsx
- frontend/src/components/BCDataGrid/BCGridViewer.jsx
- frontend/src/components/Login.jsx
- frontend/src/hooks/useOrganization.js
- frontend/src/views/Organizations/ViewOrganization/ViewOrganization.jsx
- Fix #1586.
- Minor typo corrections and aria-labelling.
- Fix Accessible header component, as it is impacting the sorting functionality within ag-grid.
> Fix: LCFS BUG - Navigating directly to organization detail errors #1586

- frontend/.dockerignore
- frontend/Dockerfile.dev
FE dockerfile was copying node_modules AFTER running NPM install meaning it used local node_modules over its own. Add a .dockerignore to prevent this.
Use explicit copy instead of copy * to easier track and see layer changes
> fix: FE Cache Fixes

- frontend/src/assets/locales/en/dashboard.json
- frontend/src/views/Dashboard/Dashboard.jsx
- frontend/src/views/Dashboard/components/cards/bceid/OrgUserSettingsCard.jsx
- frontend/src/views/Dashboard/components/cards/bceid/__tests__/OrgUserSettingsCard.test.jsx
- frontend/src/views/Dashboard/components/cards/idir/UserSettingsCard.jsx
- frontend/src/views/Dashboard/components/cards/idir/__tests__/UserSettingsCard.test.jsx
- frontend/src/views/Dashboard/components/cards/index.js
This PR adds a user settings widgets to the dashboard, providing quick access to notifications, configurations, and help options for all users.
Closes #1589
> Feat: Add User Settings Widgets to Dashboard - 1589

- frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx
- frontend/src/views/ComplianceReports/components/ReportDetails.jsx
**Restrict Edit Icon Visibility in Compliance Report Schedules**
For BCeID users:
If the compliance report status is Draft, the edit icon is displayed.
For all other statuses, the edit icon is hidden.
For Analyst users:
If the compliance report status is ReAssessed, the edit icon is displayed.
If the status is Submitted or Assessed, the edit icon is only displayed in the supporting documents section.
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=92395129&issue=bcgov%7Clcfs%7C1581)
> LCFS-1581: Edit icon appearing for IDIR users when compliance reports are in the Submitted status

- frontend/src/assets/locales/en/transfer.json
- frontend/src/views/Transfers/AddEditViewTransfer.jsx
- frontend/src/views/Transfers/components/CategoryCheckbox.jsx
- frontend/src/views/Transfers/components/__tests__/CategoryCheckbox.test.jsx
This PR disables the Category D checkbox for Analysts once a transfer has been recommended to the Director.
Closes #1644
> Fix: Disable Category D checkbox for Analysts after transfer recommendation - 1644

- backend/lcfs/web/api/compliance_report/repo.py
* We need some filters to be applied to the inner select and some to the outer
* Create two filter functions for separating the filters and apply appropriately
* Always join org and compliance period so we can filter/sort by it
> Fix: Separate where clauses for compliance report

- docker-compose.yml
- frontend/src/components/BCDataGrid/components/Editors/AutocompleteCellEditor.jsx
- frontend/src/views/AllocationAgreements/_schema.jsx
- frontend/src/views/FuelExports/_schema.jsx
- frontend/src/views/FuelSupplies/_schema.jsx
- frontend/src/views/OtherUses/_schema.jsx
> fix: LCFS - Enhance boundaries of drop down menu options in compliance reporting fuel supply #1687

- backend/lcfs/web/api/final_supply_equipment/schema.py
- frontend/src/views/FinalSupplyEquipments/_schema.jsx
- fix: kwh for fse optional, closes #1701
> fix: make kwh optional for fse

- backend/lcfs/web/api/compliance_report/schema.py
- backend/lcfs/web/api/compliance_report/summary_service.py
- frontend/src/views/ComplianceReports/components/_schema.jsx
- Fixed missing field in ComplianceReportSummaryUpdateSchema, which was causing a backend error:
`AttributeError: 'ComplianceReportSummaryUpdateSchema' object has no attribute 'is_locked'`
- Resolved amount calculation issue where values were stored as integers but calculated using decimals, leading to errors when saving lines 6 and 8. Confirmed with the user that amounts should be calculated using standard rounding (rounding to the nearest integer).
> LCFS-1760: 500 error in compliance report summary lines 6 and 8

- frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx
* BCGridBase now takes a Transaction returned from onAction and will apply it if it contains rows.
* This was changed so we can focus on the newly added cell, and it looks like this table was not updated
> fix: Return transaction instead of applying

- backend/lcfs/db/migrations/versions/2025-01-23-15-38_7f7b03241d7f.py
- backend/lcfs/db/models/notification/NotificationType.py
- backend/lcfs/db/models/user/Role.py
- backend/lcfs/db/seeders/dev/notification_channel_subscription_seeder.py
- backend/lcfs/db/seeders/dev_seeder.py
- backend/lcfs/logging_config.py
- backend/lcfs/tests/notification/test_notification_repo.py
- backend/lcfs/tests/notification/test_notification_services.py
- backend/lcfs/web/api/notification/repo.py
- backend/lcfs/web/api/notification/services.py
- backend/lcfs/web/api/user/repo.py
- backend/lcfs/web/api/user/services.py
This PR updates the logic to align with business requirements, setting default notifications for all subscriptions when a role changes. Users set to Inactive will have their settings cleared.
Backend logs now show less traceback for better clarity and maintainability. 
Closes #1703
> Feat: Update role subscription notification logic - 1703

- frontend/src/components/BCDataGrid/BCGridBase.jsx
* When scroll ends check to see if selected cell is outside viewport, if it is clear its selection / close the select.
> fix: Hide AG Grid Menus outside Viewport

- frontend/src/layouts/MainLayout/components/UserProfileActions.jsx
* Since its a button not just a link, it has extra padding causing it to move on hover / active
* Use custom CSS override for this button to fix the issues
> fix: Add custom CSS for Notification Button

- backend/lcfs/db/migrations/versions/2025-01-27-20-28_26bb41f15dc4.py
- frontend/src/views/FuelSupplies/AddEditFuelSupplies.jsx
There are some fuel types that do not autopopulate fuel category and end use:
fuel_type           |category|
Propane             |Diesel  |
Electricity         |Jet fuel|
Alternative jet fuel|Jet fuel|
**Fix**
Update end_use_type_id in energy_effectiveness_ratio. 
When selecting fuel category, autopopulate determining carbon intensity when only one option.
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=95369214&issue=bcgov%7Clcfs%7C1802)
> LCFS-1802: Not able to select the fuel category for Alternative Jet fuel in Supply of fuel in TEST

- frontend/src/hooks/useComplianceReports.js
Update line 10 when other lines update
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=94641247&issue=bcgov%7Clcfs%7C1760)
Note: This PR fixes this comment:  have Line 10 to show updates immediately upon changes made in lines 6-9? Right now Line 10 only updates if you navigate away and then return to the report
> Update line 10 when other lines update

- frontend/src/assets/locales/en/common.json
- frontend/src/assets/locales/en/transfer.json
- frontend/src/views/Transfers/components/TransferHistory.jsx
- frontend/src/views/Transfers/components/__tests__/TransferHistory.test.jsx
User login as BCeID Organization does not show name of Director:
IDIR users can see the name of Director:
> LCFS-1827: Recorded transfer in BCeID transaction history is showing director user name

- backend/lcfs/tests/compliance_report/conftest.py
- backend/lcfs/tests/compliance_report/test_update_service.py
- backend/lcfs/web/api/compliance_report/update_service.py
* Previously a supplier would be blocked if they didnt have enough credits
* Now we take as many as we can and allow it
> fix: Allow Submissions without enough credits

- frontend/src/hooks/useComplianceReports.js
* New code navigates to the main listing, so we dont need to refresh all the sub-data
* Firing the refresh in the case of return to supplier was resulting in a 403
> fix: Don't fire refresh queries when changing compliance report status

- backend/lcfs/tests/organization/test_organization_validation.py
- backend/lcfs/web/api/organization/validation.py
- frontend/src/assets/locales/en/transfer.json
- frontend/src/views/Transfers/components/TransferDetails.jsx
- frontend/src/views/Transfers/components/__tests__/TransferDetails.test.jsx
- When a BCeID user enters a credit amount exceeding their available balance, instead of triggering a 403 error, the system now automatically adjusts the amount to the maximum allowed and notifies the user of the change in the UI.
- This enhancement has been implemented on both the frontend and backend as requested.
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=95751541&issue=bcgov%7Clcfs%7C1863)
> LCFS-1863: Credit transfer credit amount maximum

- backend/lcfs/web/api/transaction/repo.py
- frontend/src/views/Transfers/components/TransferDetails.jsx
When the user exhausts their available balance, they cannot create another transfer.
The balance is set to 50,000 and the user creates a transfer for the same amount:
Then, the user cannot create another transfer:
> LCFS-1863: Fix calculation for available balance

- frontend/src/views/ComplianceReports/components/ReportDetails.jsx
When there is no documents, `Supporting Documents` section should not appear. If there is at least one doc, then show the accordion opened:
> LCFS-1925: Supporting Documents Accordion Displays Even When No Documents Are Uploaded

- backend/lcfs/tests/compliance_report/test_update_service.py
- backend/lcfs/web/api/organizations/services.py
- Reserved transaction logic was assuming negative compliance units, but we can create in reserve txns with + values
> Fix: Reserve Txn Logic

- backend/lcfs/db/migrations/versions/2025-02-11-23-51_44c6f23b71d3.py
- backend/lcfs/db/models/compliance/CompliancePeriod.py
- backend/lcfs/db/models/fuel/AdditionalCarbonIntensity.py
- backend/lcfs/db/models/fuel/EndUseType.py
- backend/lcfs/db/models/fuel/FuelType.py
- backend/lcfs/tests/compliance_report/conftest.py
- backend/lcfs/tests/fuel_code/test_fuel_code_repo.py
- backend/lcfs/tests/fuel_export/conftest.py
- backend/lcfs/web/api/common/schema.py
- backend/lcfs/web/api/compliance_report/schema.py
- backend/lcfs/web/api/compliance_report/services.py
- backend/lcfs/web/api/compliance_report/views.py
- backend/lcfs/web/api/fuel_code/repo.py
- backend/lcfs/web/api/fuel_code/schema.py
- backend/lcfs/web/api/organization/views.py
- Add compliance_period_id to additional_carbon_intensity table .
- Update models and queries to incorporate compliance_period_id
- Add migration to seed compliance_period 2024 for existing records in additional_carbon_intensity table.
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=96876391&issue=bcgov%7Clcfs%7C1945)
> LCFS-1945: Add compliance_period_id to additional_carbon_intensity table

- backend/lcfs/db/dependencies.py
- backend/lcfs/services/clamav/client.py
- backend/lcfs/tests/final_supply_equipment/test_final_supply_equipment_importer.py
- backend/lcfs/tests/final_supply_equipment/test_final_supply_equipment_services.py
- backend/lcfs/utils/constants.py
- backend/lcfs/web/api/final_supply_equipment/importer.py
- backend/lcfs/web/api/final_supply_equipment/repo.py
- backend/lcfs/web/api/final_supply_equipment/schema.py
- backend/lcfs/web/api/final_supply_equipment/services.py
- backend/lcfs/web/api/final_supply_equipment/views.py
- frontend/src/assets/locales/en/finalSupplyEquipment.json
- frontend/src/components/BCModal.jsx
- frontend/src/components/Documents/DocumentTable.jsx
- frontend/src/constants/common.js
- frontend/src/constants/routes/apiRoutes.js
- frontend/src/hooks/useFinalSupplyEquipment.js
- frontend/src/themes/components/linearProgress.js
- frontend/src/views/FinalSupplyEquipments/AddEditFinalSupplyEquipments.jsx
- frontend/src/views/FinalSupplyEquipments/FinalSupplyEquipmentSummary.jsx
- frontend/src/views/FinalSupplyEquipments/ImportFuelSupplyEquipmentDialog.jsx
* Add new importer.py to handle imports
* Add new dialog with states to go through the import process
* Use a newly spawned thread to process the import async
> feat: Add Import of FSE's

- backend/lcfs/web/api/allocation_agreement/views.py
- frontend/src/components/BCDataGrid/BCGridEditor.jsx
* This was causing the CreateAllocationAgreementSchema validation to run despite the types being defined as a union. AFAIK Flask does not like union types on views.
> fix: Remove return types from Save

- frontend/src/views/Admin/AdminMenu/components/ViewUser.jsx
- Ensures the pencil icon is only visible to users with the "Manage User" and "Administrator" roles.
Closes #1995
> Fix: Restrict Pencil Icon Visibility - 1995

- backend/lcfs/db/models/compliance/ComplianceReportStatus.py
- backend/lcfs/web/api/compliance_report/repo.py
- backend/lcfs/web/api/compliance_report/services.py
This PR includes the following improvements and fixes:
- Internal statuses are now restricted to IDIR users
- Fixed an issue where filtering for submitted statuses caused a 500 error.
- Formatted Python code for better readability and consistency
Closes #2050
> Fix: Hide internal statuses and fix submitted status filtering for BCeID users - 2050

- frontend/src/components/BCDataGrid/BCGridEditor.jsx
This PR includes the following fixes:
- Ensures the 'Indicates a required field' text is persistently visible on Notional Transfer, FSE, and Fuels for Other Use pages.
- Fixes intermittent disappearance of the text when adding rows, refreshing the page, or landing on the form.
Closes #1996
> Fix: Ensure 'Indicates a required field' text remains visible - 1996

- backend/lcfs/db/migrations/versions/2025-02-12-18-15_0d5836bb1bf8.py
- Update the mv_transaction_aggregate materialized view to properly calculated the correct transfer compliance period
- Updated this manually in each environment and add the patch to a previously run migration
> Feat: Updated Txn Aggregate MV

- frontend/src/views/FuelExports/AddEditFuelExports.jsx
- frontend/src/views/FuelExports/_schema.jsx
- fix: not being able to tab open the date picker, closes #2138 
the date range picker in FSE uses a package that does not look like we'll be able to customize to add the ability to use arrow keys to select the date range. may need to explore other alternative packages that offer this feature or at least be able to customize to add this feature. spike ticket created: https://github.com/bcgov/lcfs/issues/2184
> fix: fuel export date accessibility

- frontend/src/views/Transactions/Transactions.jsx
- frontend/src/views/Transactions/_schema.js
- fix: transaction id not sorting correctly by numerical value, closes #2069 
- refactor: bc grid viewer to new bc grid viewer 2, touches on #2152
> fix: transaction id sorting

- backend/lcfs/tests/fuel_export/test_fuel_exports_services.py
- backend/lcfs/tests/fuel_export/test_fuel_exports_views.py
- backend/lcfs/web/api/fuel_export/schema.py
- frontend/src/views/FuelExports/AddEditFuelExports.jsx
- frontend/src/views/FuelExports/_schema.jsx
- frontend/src/views/FuelSupplies/_schema.jsx
* Remove any default, Any is not a valid option for all fuel types (electricity)
* Update logic to look at unique fuel types, with the new code for EER ratios there can be many Anys per fuel type.
> fix: Properly populate endUseType in Fuel Exports

- backend/lcfs/tests/compliance_report/test_compliance_report_views.py
- backend/lcfs/web/api/compliance_report/services.py
- backend/lcfs/web/api/compliance_report/views.py
- frontend/src/views/ComplianceReports/__tests__/HistoryCard.test.jsx
- frontend/src/views/ComplianceReports/components/HistoryCard.jsx
This PR includes the following fixes:
- Hides "Draft" status from IDIR users in Compliance Report history.
- Updates filtering logic to exclude draft statuses.
- Adds tests for components.
Closes #2074
> Fix: Hide Draft Status from IDIR Users in Compliance Report History - 2074

- backend/lcfs/tests/compliance_report/test_compliance_report_views.py
- backend/lcfs/web/api/compliance_report/views.py
Extra argument in `update_compliance_report_summary` causing the issue.
[Story](https://github.com/orgs/bcgov/projects/137/views/1?pane=issue&itemId=102728397&issue=bcgov%7Clcfs%7C2256)
> hotfix/LCFS- 2256: BUG - 6, 7, 8, or 9 results in a 500 error

- backend/lcfs/tests/transaction/test_transaction_repo.py
- backend/lcfs/tests/transaction/transaction_payloads.py
- backend/lcfs/web/api/transaction/repo.py
- backend/lcfs/web/api/transfer/services.py
* Was only checking the day, did not include transactions up until the end of March 31st in Vancouver time.
> fix: Add timezone to available balance check

- backend/lcfs/tests/compliance_report/conftest.py
- backend/lcfs/tests/compliance_report/test_compliance_report_views.py
- backend/lcfs/tests/conftest.py
- backend/lcfs/tests/fuel_export/test_fuel_exports_views.py
- backend/lcfs/tests/notional_transfer/test_notional_transfer_view.py
- backend/lcfs/tests/organization/test_organization_views.py
- backend/lcfs/tests/other_uses/test_other_uses_view.py
- backend/lcfs/web/api/compliance_report/repo.py
- backend/lcfs/web/api/compliance_report/schema.py
- backend/lcfs/web/api/compliance_report/services.py
- backend/lcfs/web/api/compliance_report/views.py
- backend/lcfs/web/api/organization/views.py
- frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx
- frontend/src/views/ComplianceReports/components/AssessmentCard.jsx
- frontend/src/views/ComplianceReports/components/AssessmentRecommendation.jsx
- frontend/src/views/ComplianceReports/components/__tests__/AssessmentCard.test.jsx
* Add is newest_flag to report chain to confirm whether newer versions exist, but dont return their data
* Use this flag to control the supplemental and assessment buttons with dialogs + text
> feat: Disable new versions if there is already a draft

- backend/lcfs/web/api/calculator/views.py
fix redirect issue that is still persisting for compliance-periods endpoint
> Fix: LCFS BCeID credit calculator 2308

- frontend/src/views/FuelExports/AddEditFuelExports.jsx
- frontend/src/views/FuelExports/_schema.jsx
- Ensures RCI and compliance units are recalculated when fuel code is updated in Export fuel schedule.
- Fixes issue where editing a row didn’t reflect the updated CI in the summary.
- Clears export date from display when Determining CI option is changed.
Closes #2215
> Fix: Update RCI and Compliance Units in Export Fuel Schedule - 2215

- frontend/src/views/ComplianceReports/components/_schema.jsx
- Added missing report types (e.g. Early Issuance) to the type filter dropdown
- Ensured the dropdown options are complete and aligned with supported report types
Closes #2443
> Fix: Add Missing Report Type Filters to Dropdown - 2443

- backend/lcfs/tests/transfer/test_transfer_services.py
- backend/lcfs/web/api/transfer/services.py
- frontend/src/assets/locales/en/reports.json
- updated audit text
- transfer category null check added
> Hotfix: audit text update - 2552

- frontend/src/views/Organizations/OrganizationView/OrganizationDetailsCard.jsx
- frontend/src/views/Organizations/OrganizationView/OrganizationUsers.jsx
- frontend/src/views/Organizations/OrganizationView/OrganizationView.jsx
- Moved flash message handling from OrganizationUsers and OrganizationDetailsCard into OrganizationView.
- Prevents duplicate success messages when saving or deleting a user.
Closes #2085
> Fix: Show Flash Message Once in Organization View - 2085

- frontend/src/views/ComplianceReports/__tests__/buttonConfigs.test.jsx
- frontend/src/views/ComplianceReports/buttonConfigs.jsx
- Shows the "Issue assessment" button to IDIR Directors when a report is in "Recommended by analyst" status
- Ensures report history shows one or two recommendation entries as expected
Since Directors can now bypass the Compliance Manager, I believe there should also be a "Return to analyst" option available at this stage. I've informed the Product Owner about this suggestion.
Closes #2607
> Fix: Enable director to issue assessment from analyst recommendation - 2607

- frontend/src/views/ComplianceReports/components/AssessmentCard.jsx
- fix: icon size on the create supplemental report button, closes #2636
> fix: create assessment report icon size

- backend/lcfs/tests/internal_comment/test_internal_comment_services.py
- Added missing test cases for the `copy_internal_comments` service function.
> Feat: Add missing tests for copy_internal_comments service function

- backend/lcfs/tests/organizations/test_organizations_repo.py
- backend/lcfs/tests/organizations/test_organizations_service.py
- backend/lcfs/tests/test_organization.py
- backend/lcfs/web/api/organizations/services.py
- backend/lcfs/web/api/organizations/views.py
- frontend/src/hooks/useOrganizations.js
- frontend/src/views/Dashboard/components/cards/idir/OrganizationsSummaryCard.jsx
- frontend/src/views/Dashboard/components/cards/idir/__tests__/OrganizationsSummaryCard.test.jsx
- frontend/src/views/Transactions/components/OrganizationList.jsx
- frontend/src/views/Transactions/components/TransactionDetails.jsx
- frontend/src/views/Transactions/components/__tests__/TransactionDetails.test.jsx
Fixes bug #1789 where unregistered organizations were missing from the Dashboard Summary Widget. Now shows both Registered and Unregistered orgs, excluding Suspended and Canceled.
> Fix: Dashboard Summary Widget missing unregistered organizations - 1789

- frontend/src/views/CompareReports/CompareReports.jsx
- frontend/src/views/CompareReports/__tests__/CompareReports.test.jsx
- Fixed the column ordering logic in CompareReports to ensure the earliest report is displayed on the left and the most recent on the right.
Closes #2629
> Fix: Ensure correct column ordering in Compare mode - 2629

- frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx
- frontend/src/views/ComplianceReports/__tests__/EditViewComplianceReports.test.jsx
- Updated frontend logic to conditionally hide the "Assessment Recommendation" section for BCeID users.
- Added frontend tests to verify visibility behavior for IDIR and BCeID users.
Closes #2701
> Fix: Hide Assessment Recommendation Section for BCeID Users - 2701

- backend/lcfs/tests/organizations/test_organizations_service.py
- frontend/src/views/Dashboard/components/cards/idir/OrganizationsSummaryCard.jsx
- frontend/src/views/Dashboard/components/cards/idir/__tests__/OrganizationsSummaryCard.test.jsx
- Updated Organizations Summary Card to fetch and display all organizations without filtering by status.
- Removed unnecessary filtering logic for organization statuses in the backend tests.
Closes #1789
> feat: Show all organizations in Organizations Summary Card menu - 1789

- frontend/src/views/ComplianceReports/components/_schema.jsx
- frontend/src/views/Transactions/_schema.js
This PR includes the following changes to improve usability of the Transactions table:
- Moved the "Status" column to the far left to make it immediately visible.
- Reduced width of "ID" and "Year" columns to optimize table layout.
- Moved the "Status" column to the far left in the Compliance Report list.
Closes #2624
> Feat: Transaction view status column refinement - 2624

- backend/lcfs/web/api/compliance_report/repo.py
- backend/lcfs/web/api/internal_comment/repo.py
Fix #2908
- While retrieving internal comments for a compliance ReportID, ensure all the reportIds are included within the report chain.
> Fix: LCFS - BUG - Internal commenting #2908

- backend/lcfs/db/migrations/versions/2025-06-18-08-48_d432ee9659f.py
- backend/lcfs/db/models/fuel/FuelCodeStatus.py
- backend/lcfs/tests/fuel_code/test_fuel_code_repo.py
- backend/lcfs/tests/fuel_code/test_fuel_code_views.py
- backend/lcfs/web/api/fuel_code/repo.py
- backend/lcfs/web/api/fuel_code/schema.py
- backend/lcfs/web/api/other_uses/schema.py
- frontend/src/constants/statuses.js
- frontend/src/utils/grid/cellRenderers.jsx
- frontend/src/views/FuelCodes/AddFuelCode/AddEditFuelCode.jsx
- frontend/src/views/FuelCodes/_schema.jsx
This PR includes the following updates:
- Added "Recommended" to `fuel_code_status_enum` and table
- Updated backend models, queries, and test cases
- Adjusted frontend logic to handle and display "Recommended" status
- Enabled filtering by Recommended in the fuel code index
Closes #2591
> Feat: Add "Recommended" Status Filter to Fuel Code Index Page - 2591

- backend/lcfs/web/api/transaction/repo.py
- frontend/src/views/Admin/AdminMenu/components/AuditLog.jsx
- frontend/src/views/Admin/AdminMenu/components/UserActivity.jsx
- frontend/src/views/Admin/AdminMenu/components/UserLoginHistory.jsx
- frontend/src/views/Admin/AdminMenu/components/__tests__/UserActivity.test.jsx
- frontend/src/views/Admin/AdminMenu/components/__tests__/UserLoginHistory.test.jsx
- frontend/src/views/ComplianceReports/ComplianceReports.jsx
- frontend/src/views/FuelCodes/FuelCodes.jsx
- frontend/src/views/FuelCodes/__tests__/FuelCodes.test.jsx
- frontend/src/views/FuelCodes/_schema.jsx
- frontend/src/views/Notifications/NotificationMenu/components/Notifications.jsx
- frontend/src/views/Notifications/NotificationMenu/components/__tests__/Notifications.test.jsx
- frontend/src/views/Notifications/NotificationMenu/components/_schema.jsx
- frontend/src/views/Transactions/Transactions.jsx
- Fixed clear filter sorting in Transactions view and all other tables to use default sort.
- Added missing default sort models and updated clear filter functions for consistency.
Closes #2709
> Fix: Correct Clear Filter Sorting Behavior - 2709

- frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx
This PR fixes the error flash on report deletion to ensure a smooth success flow.
Closes #2916
> Fix: Clean deletion flow without error flash - 2916

- backend/lcfs/web/api/email/services.py
- discovered a bug where nulls were being included in some recipient lists and failing the email send.
> fix: remove nulls from potential recipients

- frontend/src/views/FuelCodes/AddFuelCode/buttonConfigs.jsx
- Hide Edit for Analysts when status is Recommended  
- Hide Save for Directors when status is Approved  
Closes #3038  
Closes #3039
> Fix: Fuel code edit/save restrictions - 3038 3039

- backend/lcfs/db/migrations/versions/2025-07-07-13-33_07cce665fabc.py
- backend/lcfs/db/migrations/versions/2025-07-25-10-31_ae2306fa8d72.py
- Moves the `ae2306fa8d72` migration to end of chain
- Fixes 500s on Fuel Code page due to missing column
Closes #1775
> Fix: Run Missing Migration - 1775

- backend/lcfs/db/seeders/dev/fuel_code_seeder.py
Add missing fuel code options for LNG and Propane, including Proxy support for Propane. Also, applied and verified in test environment.
Closes #3267
> Feat: add fuel code options for LNG and Propane with Proxy support - 3267
